app/actions/answer.ts
app/actions/question.ts
app/components/AnsweredQuestionContent/AnsweredQuestionContent.tsx
app/components/BooleanAnsweredContent/BooleanAnsweredContent.tsx
app/components/Deck/Deck.tsx
app/components/DeckForm/DeckForm.tsx
app/components/MultipleChoiceAnsweredContent/MultipleChoiceAnsweredContent.tsx
app/components/Question/Question.tsx
app/components/QuestionAction/QuestionAction.tsx
app/components/QuestionCardContent/QuestionCardContent.tsx
app/components/QuestionForm/QuestionForm.tsx
app/components/RadioInput/RadioInput.tsx
app/components/TrueFalseScale/TrueFalseScale.tsx
app/queries/deck.ts
app/queries/question.ts
app/schemas/deck.ts
app/schemas/question.ts
app/utils/question.ts
deck.md
prisma/migrations/20240425165519_rename_is_true_question_option/migration.sql
prisma/migrations/20240426152846_refactor_binary_questions/migration.sql
prisma/schema.prisma
seed.md
stories/BooleanAnsweredContent.stories.tsx
stories/Deck.stories.tsx
stories/MultipleChoiceAnsweredContent.stories.tsx
stories/Question.stories.tsx
stories/QuestionAccordion.stories.tsx
stories/QuestionAction.stories.tsx
stories/TrueFalseScale.stories.tsx

- Description:
This PR addresses the ability to create binary questions with arbitrary values for the option label instead of fixed T/F and Y/N question types.
- ClickUp links: Not applicable
AC 1:
Ability to add binary question using admin panel
AC 2:
Ability to add binary question to deck using admin panel
AC 3:
Ability to answer binary question
AC 4:
Ability to display result for binary question
In order to test this code we need to run the provided seed script inside of deck md, which will verify ability to answer binary questions.
(AC's should be self explanatory, with the caveat that you do need to set yourself as admin user through db query.)

Refactor binary questions to allow arbitrary values for labels

---

app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/NoQuestionsCard/constants.tsx

- Description:
I have just updated the style of answer page card component 
from:
To:
As it was very small fix, I did not create a ticket for it

fix: styling of no answer-page

---

app/components/LeaderboardRanking/LeaderboardRanking.tsx

- Description:
- Fix for empty wallet addresses (Script users)

Fixed Leaderboard ranking page break due empty wallet address

---

app/api/question/get/route.ts

- Description:
Correct the logic of fetching Regular Decks in Questions API
https://app.clickup.com/t/86bzqmywj
Test route /api/question/get?userId={userId}

[PROD-48] fix: correct regular decks logic

---

app/components/Bot/Bot.tsx

- Description:
Add checkbox in first time login to avoid confusion about future login. 
https://www.figma.com/design/XowL9xTYDVFSMI9bH9wA09/Chomp-UI?node-id=8300-17850&t=vjTkgvFB7jmaIHi3-0
- Linear links:
https://linear.app/gator/issue/PROD-72/prevent-user-from-registering-multiple-email-addresses
Test fresh login flow

PROD-72 Handle user login

---

app/actions/answer.ts
app/components/Deck/Deck.tsx
prisma/migrations/20240902163858_add_timed_out_to_question_answer/migration.sql
prisma/schema.prisma

- Description
Link to the task https://linear.app/gator/issue/PROD-214/create-timedout-status-for-questionanswer
updated enum for question answer status. After time for the question expires, that question is marked as timedOut

PROD-214 added timed-out question answer status

---

app/actions/answer.ts
app/components/Deck/Deck.tsx
app/components/QuestionCard/QuestionCard.tsx

- Description
- Proceed functionality was not working properly after the timer has ran out
How to test:
- start a deck
- wait for the timer to run out
- wait for 30 seconds (at least) after the "proceed" pop up shows up
- click on proceed should result in new question along with reseted timer.

Prod 270/proceed after timer runs out

---

app/components/NoQuestionsCard/constants.tsx

- Description
- Link to the Linear task: https://linear.app/gator/issue/PROD-242/remove-dollar-sign-before-reveal-at-time 
- Complete a deck and and home screen near reveal at time there should be no $ sign 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

PROD-242 removed dollar sign

---

app/components/CampaignCard/CampaignCard.tsx
app/queries/campaign.ts

- Description
- Link to the Linear task: https://linear.app/gator/issue/PROD-293/campaigns-list-campaigns-clean-ups
-Hidden decks that are marked isVisible:false
-descending order by latest active decks
-disable click for zero state decks 
-removed right arrow for zero state decks

PROD-293 updated champaigns page

---

app/components/Deck/Deck.tsx

- Description
- Link to the Linear task: https://linear.app/gator/issue/PROD-302/do-not-allow-skipping-second-order-question
- Start a deck. Before selecting the answer the skip question should be possible. After selecting the answer the percentage slider should appear and skip question functionality should not be possible

PROD-302 removed skip functionality from second order question

---

app/components/CampaignDeckCard/CampaignDeckCard.tsx

- Description
Added redirections for revealing from Campaign page
**Not sure if I understood correctly** The goal of the task was to add redirect to /history page by clicking on any of deck 
states in Campaign details page 
https://github.com/user-attachments/assets/6da3dd24-49b4-4b5d-a374-3a00c9412a8f
@Yihwan Please confirm the logic.

PORD-300 adjusted redirection to history page

---

app/campaigns/[id]/page.tsx

- Description
- Link to the task https://linear.app/gator/issue/PROD-314/fix-spacing-between-leaderboards-and-deck-counts
Go to Campaign's details page . Spacing should be as it is in the design

PROD-314 fixed spacing

---

app/campaigns/[id]/page.tsx

Some older decks do not have activeFromDate so I added createdAt to be read if there is no activeFromDate. Another alternative is to update those decks by hand in db and add them activeFromDate.

PROD-277/incorrect-deck-reveal-state 

---

app/components/DeckForm/DeckForm.tsx

- Description: Daily deck time defaults to 0:00 UTC
- New deck form should display 0:00 UTC: https://chomp-git-ma-prod-284default-daily-time-gator-labs.vercel.app/admin/decks/new
- Editing an existing daily deck should show the time that was already set: https://chomp-git-ma-prod-284default-daily-time-gator-labs.vercel.app/admin/decks/214
In this example, user's time is UTC-5

PROD-284: default daily deck time 0:00 UTC

---

app/queries/deck.ts

Description: daily deck page and home page have different logic for daily deck detection which causes an infinite loop with some combinations of time/timezone
Intended to supercede: https://github.com/gator-labs/chomp/pull/519
What are the steps to test that this code is working?
- create a daily deck
- go to /application
- expect to be taken to daily deck without loops

PROD-193: fix daily deck redirect

---

app/components/DeckForm/DeckForm.tsx

Follow up to: https://linear.app/gator/issue/PROD-284/default-daily-deck-to-the-same-time-every-day
- Description: Was mistakenly setting daily deck date for all new questions. Instead it should be blank by default and only set to midnight UTC if user selects a daily deck date. 
- Create new deck: 1) daily deck date should be empty, 2) select daily deck date -> should be set to 0:00 UTC on that day, 3) update time on same day -> new time should be accepted, 4) set a new date -> time should be reset to 0:00 UTC
- Edit a new deck. 1) Daily deck date should be what was previously set, 2) if changing datetime, behavior should be same as above.  

fix: do not set daily deck date by default

---

app/components/CampaignDeckCard/CampaignDeckCard.tsx
lib/urls.ts

- Description: Link to a deck from campaigns unless it can be revealed/claimed
Decks at the bottom should link to decks: https://chomp-git-ma-prod-323campaign-deck-links-gator-labs.vercel.app/campaigns/15

PROD-323: link to decks unless revealable or claimable

---

app/actions/deck/deck.ts
app/components/DeckForm/DeckForm.tsx

- Description
- Link to the Linear task https://linear.app/gator/issue/PROD-320/not-able-to-add-questions-to-a-deck-that-was-originally-created
- Create a new deck without any questions inside. After successfully created deck click on the edit and add questions. Submit should pass without any error. Click again on the deck details and questions should be applied. Please go through standard flow in order to check if this change breaks existing deck flow behaviour

PROD-320 enabled adding and editing decks without initial questions

---

app/campaigns/[id]/page.tsx
app/components/CampaignCard/CampaignCard.tsx
app/queries/campaign.ts

- Description
- Link to the Linear task: https://linear.app/gator/issue/PROD-301/isvisible-and-isactive-campaigns-behavior
- On staging DB I've created a Campaign (Andrej test) ID=16. Direct link to /campaigns/16 should result in 404.
- On staging DB Campaigns Orca (id = 5) and Superteam Vietnam (id=14) are marked as isActive=true and 
isVisible=false. They should not be displayed on the list but direct links should work /campaigns/5 and /campaigns/14
- On staging DB Campaign id = 12 is marked as isActive=false and isVisible = true. Direct link should work /campaigns/12  
and should be visible on the list
- For the other Campaigns, direct links should work and …

Prod 301/is visible and is active campaigns behaviour

---

app/actions/deck/deck.ts

- Add decks within tx context
- Disable deck deletion until confirmed stable
Supercedes https://github.com/gator-labs/chomp/pull/535 which had a lot of noise

fix: ability to add questions to decks

---

app/components/CampaignDeckCard/CampaignDeckCard.tsx
app/components/LoginPopUp/LoginPopUp.tsx

- Description
- Branched from https://github.com/gator-labs/chomp/tree/PROD-257/create-connect-wallet-state-on-campaigndetails. After @danijel-radomiljac resolves conflicts on his branch, I'll apply it here.
- Link to the Linear task https://linear.app/gator/issue/PROD-322/redirect-to-deck-after-logging-in-from-campaigns
- I am open to any suggestion. I did this in a rush a bit just to make it work for the breakpoint
-  Anonymous go to the campaings page. Pick one campaign and select deck. On select connect wallet should appear. After successfully connection you should be redirected to the selected deck. …

Prod 322/redirect to deck after loggin in from campaings

---

app/components/AuthRedirect/AuthRedirect.tsx

- Description
- Link to the Linear task: https://linear.app/gator/issue/PROD-313/add-auth-to-admin-routes
- Login with the account that does not have the admin rights. Type the  "/admin" url path. You should not be able to access the admin dashboard. It should result in redirect to /application page (I've decided to add redirect since it was the easiest)

PROD-313 added auth to admin routes

---

app/components/CampaignDeckCard/CampaignDeckCard.tsx

Somehow this got overridden: https://github.com/gator-labs/chomp/pull/529/files

fix: links to decks from campaigns

---

app/queries/answerPercentageQuery.ts
app/queries/home.ts

Quickfix for: https://gator-labs.sentry.io/issues/5708830076/?environment=vercel-production&project=4507686429130752&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=1
Removing these enum type checks may have some performance loss issues but should prevent the breaking error.

PROD-337: remove enum from queries

---

app/_reactQuery/useInfiniteQuestionsHistory.ts
app/actions/history.ts
app/application/decks/[id]/page.tsx
app/components/CampaignDeckCard/CampaignDeckCard.tsx
app/components/History/History.tsx
app/components/RevealDeck/RevealDeck.tsx
app/queries/deck.ts
app/queries/history.ts
app/screens/DeckScreens/DeckScreen.tsx

- Description
- Link to the Linear task https://linear.app/gator/issue/PROD-339/create-new-deck-view-for-ready-to-reveal-decks
I did ad hock changes. Strongly suggest code improvement for this part when we agree on the logic behind. Reused history component and adapted queries
Open the deck that is ready to reveal and you should see this screen.

PROD-339 added new view

---

app/components/NoQuestionsCard/NoQuestionsCard.tsx

- Description
Removes the Share & Earn (TaskOn) CTA and make the secondary button (Next deck, Go home) primary
Finish one deck to see the changes

PROD-346 Remove share & earn CTA

---

app/actions/chompResult.ts
app/actions/revealNft.ts
app/application/answer/reveal/[questionId]/page.tsx
app/components/ClaimButton/ClaimButton.tsx
app/hooks/useReveal.ts
app/queries/question.ts
package.json
prisma/migrations/20240926080510_add_reveal_nft_id_to_chomp_result/migration.sql
prisma/schema.prisma
scripts/reveal-nft.ts

@marvinmarnold there was a missing relation from ChompResult table to RevealNft table. Currently I set it as one to many relation, but it needs to be one to one. I did that because default value in one to one relation cannot be null, but I will fix that after we run a script called: reveal-nft.ts
That script will connect records from RevealNft table to ChompResult table.

 PROD-348/breakpoint-nft-reveal-issues 

---

app/hooks/useReveal.ts
app/utils/error.ts

- Description
Add try catch in Reveal hook to narrow down specific errors in Sentry and trace a reason behind the following issue:
> An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of ...
Verify next iteration of reveal issues in Sentry Dashboard
NA

PROD-316 Catch dynamic related issue in reveal

---

app/components/RevealDeck/RevealDeck.tsx

- Description
- Link to the task https://linear.app/gator/issue/PROD-353/deck-page-image-dimensions-does-not-match-campaign-page
[Before]
->
[After]

PROD-353 fixed image size

---

app/actions/history.ts

- Description
- Link to the task: https://linear.app/gator/issue/PROD-350/deck-specific-claim-all-doesnt-match-questions
Answer and reveal question for some deck that is related to some stack. Claim reward amount for that question should be claimable just from that deck reveal page, not from the other deck (History could and should be)

PROD-350 fixed condition for claim

---

sentry.server.config.ts

- Description
Load Failed errors occur when Fetch API calls fail. It usually happens on Apple devices. Following the below documentation, I have added captureConsole integration to get additional context for such errors.
https://sentry.io/answers/load-failed-javascript/
Sentry events will also show console logs of requests being made
NA

PROD-358: Enable captureConsole Integration Sentry

---

app/utils/sentry.ts

- Description
`Error: Cannot destructure property 'address' of '(intermediate value)' as it is undefined.` doesn't impact the user experience. It appears to be related to a browser extension, which is beyond our control. Ignoring this sentry error would be better option unless it starts causing any real issues.
Monitor sentry board for similar errors
NA

PROD-362 Ignore sentry error

---

app/components/ErrorBoundary/ErrorBoundary.tsx
app/error.tsx
app/global-error.tsx

- Description
Previously because we had useRouter in our error boundary and global error file catches the error from Root Layout which is out of next context causing this error sentry invariant expected app router to be mounted.
Rendering global-error and error boundary in production properly.
N/A

PROD-383: Sentry invariant expected app router to be mounted

---

lib/trackEvent.ts

- Ignore tracking errors (but logging will send to Sentry)
- await for tracking to finish, to ensure it's not accidentally skipped

fix: await tracking and ignore errors

---

app/components/HomeFeedDeckCard/HomeFeedDeckCard.tsx
app/constants/tracking.ts

- Description
This PR add `DeckClicked` mixpanel event to track the interaction of Decks from homepage
Click a deck from Expiring Soon section and verify the event from mixpanel dashboard

PROD-414 Add DeckClicked mixpanel event

---

app/actions/claim.ts

- Description
A treasury alert will be sent if treasury balance in less than 25M in an interval of 30min.
Sentry alert if treasury balance in less than 25M
N/A

chore: updated treasury alert invoke tag and amount

---

app/components/QuestionCard/QuestionCard.tsx

- Description
Resolved the hydration error from question card date mismatch in server and client by showing the date after client loads. 
It should not throw hydration error in sentry or console in the PWA from question answer page
N/A

fix: show formatted date after hydration in question card

---

app/actions/leaderboard.ts
app/components/Deck/Deck.tsx
app/components/Question/Question.tsx
app/components/QuestionAction/QuestionAction.tsx

- Description
It adds debounce to avoid too many requests at same time if user drags the slider continuously. It will delay the tracking call by 0.5 secs after percentage value changes.
Answer second order and drag slider continuously. Verify the events recorded in mixpanel dashboard. It shouldn't hit too many requests at same time.

PROD-448 Debounce Second Order Selection Tracking

---

app/components/QuestionCard/QuestionCard.tsx

- Description
Timer wasn't moving after the previous fixes so this pr make sure that we only show timer after client hydration is complete
N/A

fix: load timer after hydration completes

---

app/actions/claim.ts

- Set low defaults so we don't get warnings in preview branches.
- I already set prod values higher on vercel

feat: env vars for treasury alerts

---

app/actions/leaderboard.ts
app/utils/question.ts

@marvinmarnold We can update MINIMAL_ANSWERS_PER_QUESTION to 5. Also I needed to divide questionAnswers.length with questionOptions.length in getTotalNumberOfDeckQuestions function. Because if we have multi choice question, and that question has 4 answers by one user. It is actually only one answer, because we are storing answer for each option of a question in a db.

PROD-450/allow-questions-to-be-revealed-with-only-3-answers 

---

prisma/migrations/20241030104838_add_telegram_username/migration.sql
prisma/migrations/20241108065629_add_unique_deckid_userid/migration.sql
prisma/schema.prisma

- Description
Previously it was possible to invoke the answer question endpoint and get as many point as user want to prevent that now we have db constraint to prevent duplicate entry for the same userId and questionId and for deckId and questionId
No duplicates answer point for the same deck or question id.
N/A

PROD-402: add db constraint on fungibleAssetTransactionLog.

---

__tests__/actions/answer/answer-question.test.ts
app/actions/answer.ts

- Description
- Link to the task -> https://linear.app/gator/issue/PROD-460/prevent-updating-question-once-answered. 
After answering the question user should not be able to answer to the same question again. Right now, there is a check if someone triggers answer action and that question has already answered (status === 'submited') then we throw an error.
Go to some deck in order to answer the question. Before answering open the network tab. Pay attention after submitting to the network tab and select the answer action. Copy the cUrl as it is provided in the screenshot:
Paste that in your terminal and as a result there should be an error that says that user …

PROD-460 added question answer status check

---

app/components/ClaimShareDrawer/ClaimShareDrawer.tsx
lib/error.ts

- Description
Sometimes share claim all drawer can't fetch the preview link and recently we moved it into try-catch. PR add patch to record that error in Sentry
Verify from Sentry Dashboard after claim all
NA - Refactor

fix: Add sentry capture in share claim all drawer

---

__tests__/queries/stack/get-stack.test.ts
app/queries/stack.ts

- Description
Updated stacks code to show first the expiring date based on whichever is expiring first comes first, than show upcoming decks based on whichever is upcoming first based on activeFromDate and then show expired decks based on whichever expired first comes first.
Decks must be sorted based on the above comment.
N/A

Prod 594: adjust deck stack new

---

app/actions/chompResult.ts
app/actions/claim.ts
app/actions/history.ts
app/components/ClaimButton/ClaimButton.tsx
app/queries/mysteryBox.ts

- Description
Stops double claiming in any case with valid conditions on query and fix the claim error capture issue with flush
NA
NA

PROD-628: Fix claim action and sentry sanity check

---

app/utils/claim.ts

- Reverts change in: https://github.com/gator-labs/chomp/pull/809/files
- May require follow up work to set compute limit even when there is no token account

fix(PROD-668): set compute units unless a token account must be created 

---

app/components/DashboardUserStats/DashboardUserStats.tsx
app/queries/home.ts

- Description
The issue here was that user stats was displaying the number of claimed rewards from questions. This change also takes into account the claimed rewards from Mystery boxes. I've not written any additional queries. I've used methods for rewards calculations that was already implemented in Mystery box case. Description of the task does not give you exact context so check pinned conversation in the task.
- Link to the Liner task https://linear.app/gator/issue/PROD-595/change-mystery-box-text-to-always-say-won-and-refer-to-all-bonk-won-to
Before updates:
After updates: …

PROD-595 updated calc and text

---

app/actions/chompResult.ts
app/hooks/useReveal.ts

Added questionIds in extra as it is an important parameter while debugging failed reveals.

fix: refactor sentry tracking for failed reveals

---

components/MysteryBox/MysteryBox.tsx

This pr fix the error mentioned in the attachment.

feat: add next dynamic for lottie

---

.github/workflows/test.yml

Fixes build process to expect a git branch name from Vercel, instead of a SHA. SHAs can be ambiguous when the same commit shows up in multiple branches.

fix: ref as branch not SHA

---

app/queries/home.ts

- Description
There were a reload issue in reveal cards in mobiles when user have ~500 or more reveal cards.

fix: limit reveal cards to 100

---

app/utils/sentry.ts

- Description
It ignores TypeError: Cannot assign to read only property 'request' of object '#<c>' in Sentry as it relates to extension.
NA
NA

PROD-613: Ignore TypeError in Sentry

---

app/components/ClaimShareDrawer/ClaimShareDrawer.tsx

Linear Ticket: https://linear.app/gator/issue/PROD-605/shareclaimallerror-failed-to-fetch-link-preview
- Description
ClaimShareDrawer useEffect was running after the history page renders and fetches the preview link even if there isn't any tx hash.
No shareclaimerror on history page render.
N/A

feat: fetch link preview after drawer open

---

__tests__/utils/getUsernameForLeaderboard.test.ts
app/components/LeaderboardRanking/LeaderboardRanking.tsx
app/utils/getUsernameForLeaderboard.ts

Link to the Linear task 
https://linear.app/gator/issue/PROD-664/400-error-on-all-time-leaderboard-on-stagingchompgames
- Description
I've managed to reproduce it on staging via wallet address that Yihwan mentioned in the task, unfortunately (luckily) not on PROD. I think something is related to accounts (wallets) so I've added conditional checks that will prevent breaking the page.
- After the fix

PROD-664 added check for wallet address in rank items for all time leaderboard

---

__tests__/queries/stack/get-stack-results.test.ts
app/queries/stack.ts
app/utils/decimal.ts

Update query to not fetch all chomp results in the database when we are querying in an unauthenticated session.
Prevents large amounts of data being sent to the frontend.

PROD-684: Fix slow query for unauthenticated sessions.

---

__tests__/actions/chompmas-mystery-box.test.ts
__tests__/actions/credits/updateTxStatusConfirm.test.ts
__tests__/actions/credits/updateTxStatusFinalized.test.ts
__tests__/actions/mystery-box.test.ts

Fix tests: don't generate wallet addresses >= 44 chars.
Faker doesn't include the 0x prefix in its length limits.

PROD-697: Fix flaky Chompmas tests

---

components/MysteryBox/MysteryBox.tsx

Hide "View credits" button if no credits are in the box.
With credits:
No credits:

PROD-655: Hide "View credits" button if no credits are in the box.

---

app/actions/deck/deck.ts
app/actions/jwt.ts
app/application/answer/page.tsx
app/application/decks/[id]/page.tsx
app/components/AnswerResult/AnswerResult.tsx
app/components/Avatar/Avatar.tsx
app/components/DeckForm/DeckForm.tsx
app/components/Leaderboard/Leaderboard.tsx
app/components/Navbar/Navbar.tsx
app/components/PollResult/PollResult.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/components/Profile/Profile.tsx
app/components/ProfileForm/ProfileForm.tsx
app/components/RankingCard/RankingCard.tsx
app/components/TransactionProfile/TransactionProfile.tsx
app/queries/deck.ts
app/schemas/deck.ts
app/screens/DeckScreens/DeckScreen.tsx
prisma/migrations/20250120180401_add_author_and_author_image_url_in_decks_table/migration.sql
prisma/schema.prisma

- Description
- Link to the task https://linear.app/gator/issue/PROD-682/add-deck-author-to-deck-info-page. 
- Admin should be able to add author name in "Deck Author"section while creating or editing deck.
- Admin should be able to add author image in "Deck Author Image" section while creating or editing deck.
- Both filed are optional
- Validation for image is set to the same "Default image size" that we have through whole app
- Deck author validation is set to minimum 5 chars. We can add upper limit later
- You'll see on many places border colour update, I've updated it to the colours that should be there. But the update was required due to Avatar image default border colour that was overwriting any colour from …

Prod 682 author image fix

---

app/application/answer/reveal/[questionId]/page.tsx
app/application/rewards/page.tsx
app/queries/question.ts
components/HistoryNew/QuestionCard.tsx
lib/question.ts

Previously the reveal answer page links were not working. This is because the answer page wasn't set up for credits questions. I've updated the page to accommodate both legacy questions and credits questions, with two caveats:
- The rewards will be zero until the user has claimed a mystery box.
- For credits questions I'm not sure yet how we determine if the user got the second order right (having neither a ChompResult nor a mystery box prize).
The PR also has UI fixes for the rewards history page:
- Makes the entire question clickable instead of just "View Answer".
- Adds margin at the bottom of the page.

PROD-741: Credits UI fixes and answer page credits implementation

---

app/application/answer/reveal/[questionId]/page.tsx
app/queries/history.ts
components/HistoryNew/QuestionCard.tsx

User would be able to see answers once reveal date is passed regardless their participance. 
- Applied on history tab each question
- Same with stack > deck > questions

PROD-749: User can view revealed answers without participance

---

app/application/answer/reveal/[questionId]/page.tsx
app/components/PollResult/PollResult.tsx
app/components/QuestionAnswerLabel/QuestionAnswerLabel.tsx
app/queries/history.ts
components/HistoryNew/QuestionCard.tsx

Show second order result greyed out until we know the result.
The PR also fixes the question card status query which was broken in a recent commit.
Until mystery box is opened:
Post opening:

PROD-774: update second order report on answer page

---

__tests__/actions/mystery-box-history.test.ts
app/actions/mysteryBox/fetchHistory.ts

Problem: 
There were some card in history page with 0bonk, 0credit and with unopened state.
Issue: 
For triggers like ClaimAllCompleted/RevealAllCompleted we don't have any trigger to prize to relation now. Instead it is now with triggerType Combined to prize. But fetchHistory query returned the trigger without prize cause the corrupt data. 
Solution:
Updated query for fetch history to show data if prize is available for a trigger. 
Extra: 
1. Fixed test
2. Show total mystery box reward
3. Show tag for validation reward.

fix: only show mystery box with a prize in history tab

---

__tests__/actions/threat-level.test.ts
__tests__/lib/bots.test.ts
app/api/cron/detect-bot-activity/route.ts
lib/bots.ts
lib/jwt.ts
prisma/migrations/20250210225409_add_threatlevelchangedat_column/migration.sql
prisma/migrations/20250210225409_add_threatlevelwindow_column/migration.sql
prisma/schema.prisma
types/bots.ts
vercel.json

Pulls suspected bot users from the mechanism engine and updates the database.
Runs 10 minutes before every hour so questions that are about to reveal are included in the analysis.
The production endpoint is not deployed yet.

PROD-689: Automated banned users

---

__tests__/actions/mystery-box-history.test.ts
__tests__/queries/home/deck.test.ts
__tests__/queries/home/get-free-deck.test.ts
__tests__/queries/home/get-premium-deck.test.ts
__tests__/queries/stack/get-stack.test.ts

Get Premium Deck and Free Deck tests were giving flaky Transaction API prisma error (couldn't able to start in given time). Patch to fix this issue and cleanup data after test is completed.
Other tests didn't delete data and stale data is piling up in the db. I audited those tests and sanitized all the stale crops.

PROD-777: Cleanup test data and Flaky Prisma Error

---

lib/jwt.ts

The user ID and wallet details were removed from the Sentry reporting in a recent merge.

PROD-790: Reinstate user ID / wallet to threat level reporting.

---

components/BuyBulkCreditsDrawer.tsx

Fixes a few issues with the bulk buy credits drawer:
- Show SOL instead of $.
- If the balance lookup fails, don't limit the input (the balance SDK call seems not to work on staging/prod, unsure why...).
- First press of "+" goes to 1 instead of 0.
- Max value on input field should be in terms of credits rather than SOL.

Fix: credits drawer tweaks

---

app/queries/question.ts

Fix rewards display on answer page by not pulling mystery box records for all users.

PROD-813: Fix rewards display on answer page

---

app/components/AdminBinaryQuestionGeneratorForm/AdminBinaryQuestionGeneratorForm.tsx
app/components/AdminMultiChoiceQuestionGeneratorForm/AdminMultiChoiceQuestionGeneratorForm.tsx
app/components/DeckForm/DeckForm.tsx

Admin will see 0 credit as default. Adding not null validation in schema would affect the legacy questions.

PROD-795: Not Allow Null Credit Cost 

---

app/utils/sentry.ts

This error was previously ignored, but due to a change in the request object type, it now reflects that change in a similar error.

PROD-613: Add ignore sentry error

---

.env.example
app/components/DeckForm/DeckForm.tsx
app/utils/algo.ts

- Auto populate `revealTokenAmount` input in admin panel unless manually set.
- Send cost and reveal amounts to mechanism engine.
This update will need to be coordinated with the mechanism engine as we are changing a parameter's meaning and expected value by orders of magnitude.

PROD-805: Auto populate revealTokenAmount input in admin panel

---

__tests__/queries/history/get-new-history-query.test.ts
app/queries/history.ts

Issue: Previously we used to show incorrect tag even though user had given a correct answer. 
Resolution: This PR update the query parameters to show tags correctly.

fix: update get new history query

---

__tests__/queries/history/get-new-history-query.test.ts
app/queries/history.ts

The commit update the query to not show data with future reveal date but mistakenly undo the previous changes 
https://github.com/gator-labs/chomp/commit/8d0b1e58d07b957df88de7d938257c15aa0546f6
This Pr will add the changes back and update the test.

Prod 844/history tab fix

---

__tests__/queries/home/deck.test.ts
__tests__/queries/stack/get-stack.test.ts

home/deck.test.ts and get-stack.test.ts are flaky tests. We reviewed the logic thoroughly and fixed time zone issue but worked out. We can rewrite these tests later. Skipping it for now.

Skip flaky tests

---

app/actions/claim.ts
app/actions/mysteryBox/open.ts
app/actions/mysteryBox/openMysteryBoxHub.ts
app/utils/sendBonk.ts
lib/claim.ts
lib/error.ts
lib/mysteryBox.ts

- openMysteryBoxHub query validate that MBP should be unclaimed or dismissed
- It will allow new or unopened MB with unclaimed or dismissed MBP
- Better Error Handling in openMysteryBoxHub action and sendBonk util
- Fix FATL update query to handle values
- Add retry logic if prisma tx API fails
- Add similar sanity check on transaction confirmation verification like credit payment to capture tx simulation failure
Few changes won't be related but I changed utils/claim.ts --> utils/sendBonk.ts so legacy mysteryBox code is refactored.

PROD-849: Fix Open MysteryBox Hub

---

__tests__/actions/mystery-box-history.test.ts
app/actions/mysteryBox/fetchHistory.ts

Description
Update the code in a way that we only show validation and campaign box in history
Reason
Legacy box doesn't have openedAt date causing it to show not opened state.

fix: only show validation and combined mb in history

---

app/utils/sendBonk.ts

This change handle the getParsedTransaction() RPC method for VersionedTransaction. It will throw an error if this argument is not present. The transaction is successful but verification fails due to the missing arg. Fortunately, this issue didn't interrupt the flow in sendBonk as it returns signature. It had just log the error in Sentry.
https://gator-labs.sentry.io/issues/6331582431/events/71e23881da05460880c2f983f73f1b44/
Ref:
https://www.quicknode.com/docs/solana/getParsedTransaction
https://solana.com/developers/guides/advanced/versions#how-to-set-max-supported-version

fix: handle parsedTx for versioned tx

---

__tests__/queries/home/get-next-deck-id-query.test.ts
app/queries/home.ts

Handle null previous deck in getNextDeckId query (home). Add a test case to handle this edge case.

PROD-871: Fix 500 Deck Page Error

---

app/components/MysteryBoxReward/MysteryBoxReward.tsx

Process state for open mystery box flow. User won't be able be able to invoke the same action multiple times.

feat: add state to prevent multiple clicks on mystery box open flow

---

app/utils/sendBonk.ts

Fix the current issue of BlockHeightExceed in confirmation and it's [deprecated](https://solana.com/docs/rpc/deprecated/confirmtransaction). 
Migrate to getSignatureStatus method: https://solana.com/docs/rpc/http/getsignaturestatuses

PROD-891: Ultimate Transaction Status Checker

---

__tests__/actions/credits/updateTxStatusConfirm.test.ts
__tests__/api/process-credits/route.test.ts
actions/credits/getPackList.ts
actions/credits/initiatePurchase.ts
app/api/cron/process-credits/route.ts
components/BuyBulkCreditsDrawer.tsx
components/CreditPackList.tsx
components/CreditPackListItem.tsx
hooks/useCreditPurchase.ts
lib/credits/createChainTx.ts
lib/credits/createTransaction.ts
lib/credits/getCreditPack.ts
lib/credits/processCreditsTransaction.ts
lib/credits/processTransaction.ts
lib/credits/updateTxStatusConfirm.ts
prisma/migrations/20250305234145_add_credit_packs/migration.sql
prisma/migrations/20250306200809_add_creditpack_to_chaintx/migration.sql
prisma/schema.prisma

This implements the credit pack options in the bulk buy modal.
Credit packs are stored in the database. They store the current credit cost as well as the discounted rate, so can be referenced in the FATL to see historical prices (if the credit cost ever changes). That does mean the existing records should be immutable though (a possible weakness of this design... easy to forget). The current prisma schema uses UUIDs for the packs, but this could be changed to a descriptive const-style string.
Unfortunately. I had to duplicate the `creditPack` reference in `ChainTx` as the process-credits cronjob needs it to recover any failed transactions. It's not ideal, but keeping the pack info only in `ChainTx` also doesn't feel right. I'm open to alternative ideas.
The credits logic is a bit …

PROD-753: Bulk purchase credits in purchase credits modal

---

vercel.json

Disabling the cron job as a temporary measure until a permanent 
solution can be implemented. This prevents the failed transaction from getting confirmed.

chore: temporarily remove process-credits cron job pending permanent fix

---

components/CreditPackListItem.tsx

Add "per credit" label for credit pack price.
Also make greyed out text more visible when selected.

PROD-912: Add "per credit" label for credit pack price.

---

app/components/MysteryBoxReward/MysteryBoxReward.tsx
components/MysteryBoxHub/OpenMysteryBox.tsx

Ensure that the button in the mystery box hub can't be clicked again after a claim has completed (or during the claim process).

PROD-917: Remove lag from mystery box button state.

---

app/application/answer/reveal/[questionId]/page.tsx

During the first render of the page, the URL parameters are (sometimes) unavailable, which means we send a request to the backend with an undefined question ID, triggering a Prisma error.
Returning a promise triggers suspense (i.e. the Chompy loading screen) further up the tree. There is a better solution to this problem, but we'd need NextJS 15.x.

PROD-914: Don't query backend if parameters are unavailable

---

app/components/DeckForm/DeckForm.tsx
app/schemas/deck.ts

Make the credit cost control in the admin dashboard an input field so any amount can be entered.

PROD-963: Make credit cost an input field rather than select box.

---

vercel.json

Run bot detector 8 minutes later so there is less of a chance of conflicting with the replica job. https://gator-labs.slack.com/archives/C06054PPNSY/p1742808063639379

fix: give bot detector more buffer after replica

---

next.config.js

Error seems to be due to body size limit. Increased significantly to test this theory. Can only easily be tested in the wild by real users. 
https://nextjs.org/docs/14/app/api-reference/next-config-js/serverActions#bodysizelimit

fix: increase max body size server actions

---

prisma/migrations/20250328143906_add_questionanswer_index/migration.sql
prisma/schema.prisma

This adds an index to the QuestionAnswer table. I already added the index to the prod database for testing (I will remove it so Prisma recreates it when I do the release).

PROD-956: Add INDEX to QuestionAnswer table.

---

app/components/ProfileForm/ProfileForm.tsx

If an existing username is entered, we currently show both success and error toasts and redirect back to the homepage.

PROD-984: Don't move from profile form if profile update failed.

---

__tests__/lib/ask/addToCommunityAskList.test.ts
app/api/ask/route.ts
lib/ask/addToCommunityDeck.ts
prisma/migrations/20250330205841_add_specialid_column_to_stack/migration.sql
prisma/schema.prisma

Implement assignment to community deck feature.
Some of the complexity from the ticket wasn't needed in the end:
- We can easily identify the draft deck as it belongs to the community stack (since it is added there immediately after creation).
- The `addedToDeckAt` field is available as `DeckQuestion.createdAt`.
I have added a `specialId` field which gives us a way to identify special decks such as the community ask deck; we have the flexibility to add others in the future.

PROD-965: Ability to assign a submitted question to a community deck

---

app/components/Stack/Stack.tsx
app/components/StackForm/StackForm.tsx
app/stacks/[id]/page.tsx
lib/ask/addToCommunityDeck.ts

Fixes:
- Don't die if there is no stack image (currently the case for the auto-created community stack)
- Don't show the community ask stack info page if the ask feature flag is unset.
- Set community stack to invisible initially.
- Add a badge in the admin panel for special stacks.

Fix: community ask stacks page

---

app/components/Deck/Deck.tsx
app/components/QuestionCard/QuestionCard.tsx

Pause question timeout after user clicks the Chomp button.
This avoids a race condition where the user clicks the button just before the timer elapses.

PROD-982: Pause question timeout after user clicks the Chomp button.

---

__tests__/queries/history/get-decks-history.test.ts
__tests__/queries/history/getAnsweredDecksForHistory.test.ts
__tests__/queries/home/deck.test.ts
app/actions/history.ts
app/api/history/deck/route.ts
app/application/history/page.tsx
app/components/HomeFeedDeckCard/HomeFeedDeckCard.tsx
app/components/NewHistoryHeader/NewHistoryHeader.tsx
app/components/StackDeckCard/StackDeckCard.tsx
app/queries/history.ts
components/Deck/DeckWrapper.tsx
components/HistoryNew/HistoryDeckCard.tsx
components/HistoryNew/HistoryList.tsx
components/NewHistoryHeader/NewHistoryHeader.tsx
lib/history/deck.ts
tailwind.config.ts
types/history.ts

New toggle in history section to show unanswered deck when the toggle is off with dark background color. Answered deck will be shown in purplish color 
Key points
- Default behavior is for 'only deck's i've answered' to be on
- Add info popup
- Ordering of cards is not impacted by the filter

feat: add new history header

---

app/queries/history.ts
components/HistoryNew/HistoryList.tsx

Fixes the issue with 0 BONK displayed in the deck history. It was due to an invalid date comparison between a Date object and string.

PROD-1017: Fix 0 BONK in deck history

---

.github/workflows/test.yml

Create isolated Neon branch for every Github branch being tested. If branch is main, then create a new Neon branch every time. Otherwise, reuse the same branch. Start with an empty DB. Schema only.
Follow-up to: https://github.com/gator-labs/chomp/pull/1087
--
Context from Slack: https://gator-labs.slack.com/archives/C06054PPNSY/p1743784638470569
The overall goal is to reduce test flakiness. One of the causes of the flakiness was that the Vercel preview link that we use for manually testing each feature branch currently uses the same DB that is used by the tests.
This would mean that tests would fail because of activity from visiting web preview. Or web preview may see weird behavior from tests running.
This PR makes it so that:
- every Github branch has a Neon DB branch created just for …

build(PROD-1001): run tests in isolated branch

---

__tests__/queries/home/get-next-deck-id-query.test.ts
app/queries/home.ts

The hide from homepage flag in the admin panel (for stacks) now hides decks from the next deck rotation.

Use hideFromHomepage flag to remove decks from the "next" rotation.

---

actions/answers/answerQuestion.ts
lib/ask/addToCommunityDeck.ts
prisma/migrations/20250412214900_add_ask_reward_triggers/migration.sql

Switch to triggers for ask rewards.
I created a table `AskQuestionAnswer` in the main ask branch to track answer / user ID combos in the FATL as it avoids a giant mess with multiple relations between tables.
Not totally convinced this is better than the non-trigger approach, but don't have a strong opinion.

Apply ask rewards using a DB trigger.

---

.github/workflows/test.yml

The schema-only option creates a new root branch. We are only allowed a limited number of root branches so we cannot create a new schema-only branch liberally. schema-only prevents the DB from having any data when test starts. But that really shouldn't be a requirement for our tests anyways.
An alternative approach would be to delete branches after test completes. But that will make debugging errors more difficult.

fix: do not use schema-only

---

__tests__/actions/ask/question.test.ts
app/schemas/ask.ts

Update the error message on ASK components Question and Answer Choice
The error was left under the input field since that was an option on the issue.
The new error text should appear as:
`This field can have up to 40 characters.`
Also added the next error to match them both:
`This field must have at least 5 characters.`

PROD-1033 update error state of ask copy

---

components/AskWizard/AskImagePreview.tsx

- Close modal with click outside of image or press Escape.
- Limit max height of modal so that the X button is always visible.

PROD-1032: Close ask image preview on click outside or esc

---

actions/answers/markQuestionAsSeenButNotAnswered.ts
app/components/Deck/Deck.tsx
app/hooks/useInterval.ts

More visibility for error when marking errors as seen, I have some suspicions about the behavior of questions when this error happens, this is as part of the investigation for 1039 skipping of questions, nobody is able to reproduce the bug still but some users say it happens

add logging for error when marking questions as seen

---

__tests__/db/triggers/ask-points.test.ts
__tests__/lib/v1/answerQuestion.test.ts
__tests__/v1/questions/answer.route.test.ts
app/queries/history.ts
app/v1/questions/[id]/answer/route.ts
lib/mysteryBox.ts
prisma/migrations/20250508151300_qualify_trigger_table_refs/migration.sql

This resolves an issue which was causing the question skipping phenomenon. The problem was in the ask trigger which fails randomly if we don't explicitly set a schema prefix.
I imagine there are other instances of this issue in other raw queries throughout the app so we should definitely do an audit, but for now this one is in the answer code path and I believe responsible for the failures we've been seeing.
Edit: I went ahead and found/fixed the other instances of unprefixed tables. This PR also has some other lint fixes.

PROD-1039: automatic skipping of questions (2)

---

.github/workflows/test.yml
README.md

- Tests are failing on main when re-run because the branch name doesn't change. Added the runId to the branch name so it will be unique every time.
- Also added a trivial documentation change. This was just for testing tests.

fix(PROD-1055): rerun tests on main without failure

---

__tests__/actions/question/generateTestQuestion.test.ts

Disable `generateTestQuestion()` test for now as it causing timeout issues. This is only for dev use anyway.

Disable generateTestQuestion tests for now; update description.

---

__tests__/v1/questions/answer.route.test.ts
__tests__/v1/questions/getQuestions.test.ts
__tests__/v1/questions/update.route.test.ts
app/schemas/v1/answer.ts
app/schemas/v1/update.ts
app/v1/questions/route.ts
lib/v1/getQuestions.ts
lib/v1/updateQuestion.ts

- Add GET route to existing /v1/questions API route
- Only return desired subset of question info
- Also updates answer endpoint so that it accepts decimal values

feat: GET /questions endpoint

---

__tests__/lib/v1/answerQuestion.test.ts
__tests__/v1/questions/answer.route.test.ts
lib/v1/answerQuestion.ts

For binary questions, require 1st order option to be the same as 2nd order option.

fix(api): answer enforce 1st order = 2nd for binary

---

__tests__/lib/v1/answerQuestion.test.ts
__tests__/v1/questions/answer.route.test.ts
app/v1/questions/[id]/route.ts
lib/v1/answerQuestion.ts
lib/v1/transforQuestionAnswers.ts

https://linear.app/gator/issue/PROD-1123/api-enforce-binary-1st-order-=-2nd-order
https://linear.app/gator/issue/PROD-1118/api-get-question-results-should-return-scores
- Restrict 2nd order option for binary
- Return answerScores and bestOption

fix: API fixes

---

__tests__/v1/questions/route.get-question.test.ts
app/v1/questions/[id]/route.ts
lib/v1/transforQuestionAnswers.ts

Prisma throws a terminal exception if you try fetching a number field with NaN value. We have to instead use raw SQL, then convert to NaN -> null.

fix(api): convert optionScore NaN to null

---

app/application/rewards/page.tsx
lib/error.ts

https://linear.app/gator/issue/PROD-126/error-an-error-occurred-in-the-server-components-render-the-specific
Based on the Sentry error, it seems most likely that one of the promises is failing and causing the whole page to crash. We know we experience timeouts and db connection starvation occasionally, which may be the source of intermittent failures.
This PR:
1. introduces retries to these requests
2. sends more granular error message to sentry so we can identify the root cause

fix(PROD-126): retry rewards page failures

---

app/components/Deck/Deck.tsx

https://linear.app/gator/issue/PROD-1130/investigate-random-question-skipping-bug-on-decks-reported-by-user
We used to move to next question if problem marking question as seen. This led to a bug where we would skip questions if there was an error. We removed that, so now users may potentially see the same question again.      
Replaces https://github.com/gator-labs/chomp/pull/1182/files which had changes trying to address the root cause. But surface area of changes is too big.

fix: disable accidental question hopping

---

app/application/history/page.tsx

https://linear.app/gator/issue/PROD-1144/remove-unnecessary-data-fetching-from-history-page
Removed old code only relevant pre-credits. Increases load time of history page.

fix(PROD-1144): remove precredits logic from history

---

__tests__/actions/answer/answer-binary.test.ts
__tests__/actions/answer/answer-credit.test.ts
__tests__/actions/answer/answer.test.ts
__tests__/actions/answer/markQuestionAsSeenButNotAnswered.test.ts
__tests__/actions/credits/updateTxStatusConfirm.test.ts
__tests__/actions/get_alltime-leaderboard.test.ts
__tests__/actions/leaderboard.test.ts
__tests__/actions/mystery-box.test.ts
__tests__/actions/open-mystery-box-hub.test.ts
__tests__/api/process-credits/route.test.ts
__tests__/db/triggers/ask-points.test.ts
__tests__/db/triggers/user-balance.test.ts
__tests__/lib/ask/addToCommunityAskList.test.ts
__tests__/lib/credits/chargeUserCredits.test.ts
__tests__/lib/mysteryBox/get-breakdown.test.ts
__tests__/queries/get-validation-reward-question.test.ts
__tests__/queries/home/get-total-claimed-credit.test.ts
__tests__/queries/home/get-total-claimed-points.test.ts
__tests__/queries/home/streak.test.ts
lib/credits/getCreditBalance.ts
lib/points/getPointBalance.ts
prisma/migrations/20250601170000_add_userbalance_view/migration.sql
prisma/migrations/20250604124636_add_userbalance_table/migration.sql
prisma/migrations/20250604170000_add_userbalance_trigger/migration.sql
prisma/schema.prisma

Add a user balance table to track actual user balances and avoid constant summing over the FATL.
I was initially going to go with a materialised view but I think this approach is more efficient.

PROD-1142: Create aggregate user balance table

---

app/components/BackButton/BackButton.tsx

https://linear.app/gator/issue/PROD-1138/create-fix-for-back-arrow-navigation-issue-in-prod-1137
- Overrides back logic for specific routes.
- Imagine a user visiting pages in the following order: A -> B -> C -> B
- When the user clicks the back button, we sometimes want to navigate to A, not C.
- But because this may not be the case for all routes, we need to be able to override the default back behavior.
- One gotcha with route matching is the dynamic part of URLs. In this case, we want to intercept `/application/decks/123`. This PR assumes that all of our IDs are integers and that we don't have integers in any other part of our URLs.

feat: override back logic for some pages

---

__tests__/lib/answerStats/getStats.test.ts

https://linear.app/gator/issue/PROD-1154/fix-stats-tests
Test setup writes a lot to DB, causing setup and the first test afterwards to fail. This PR increases timeout for the test.

fix(PROD-1154): increase timeout of stat test db txs
