gator-labs/chomp

app/components/NoQuestionsCard/NoQuestionsCard.tsx

old link not working, this is new one

fix telegram link

---

README.md
app/actions/demo.ts
app/actions/jwt.ts
app/application/profile/page.tsx
app/components/ResetAccountDataButton/ResetAccountDataButton.tsx
app/components/Tag/Tag.tsx
app/layout.tsx
package.json
yarn.lock

- Description: PR adds reset data button and demo mode indicator for https://app-demo.chomp.games/
- ClickUp links: https://app.clickup.com/t/86bykbeym

Add demo environment

---

.github/workflows/migrations.yml
README.md
package.json
prisma/migrations/20240515172459_add_streak_and_time_to_answer/migration.sql

- Description: Run migrations when opening a PR into `main` or when merging into `prod`.
- Related to: https://github.com/gator-labs/chomp/pull/147

build: migrate in workflow

---

app/queries/home.ts

- Description: this PR fixes time formatting for averageTimeToAnswer

fix averageTimeToAnswer format

---

app/queries/home.ts

Value is stored as milisecond not second

Patch parsing result to miliseconds not seconds

---

.github/workflows/migrations.yml

run migrations only on pr close

---

app/components/Button/Button.tsx
app/screens/LoginScreens/constants.tsx
app/screens/TutorialScreens/RevealScreen/RevealScreen.tsx

https://app.clickup.com/t/86byv6rmc
https://app.clickup.com/t/86byv6g3v

Onboarding and slideshow fixes

---

app/components/TransactionProfile/TransactionProfile.tsx

- Description:
Add link to quick profile
https://app.clickup.com/t/86bywd0eq

Add profile link to quick profile

---

app/components/HomeFeedEmptyQuestionCard/HomeFeedEmptyQuestionCard.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx

- Description:
Add action on click for check out others
https://app.clickup.com/t/86byn5e14
Added special item to end of list, only appears if less then 5 items. And reveal on click.

Add reveal action to check out others and special card to list

---

app/actions/chompResult.ts
app/actions/claim.ts

- Description:
There was a mix up with reveal and claim action states.

Patch reveal and claim actions

---

app/application/answer/deck/[id]/page.tsx
app/application/answer/page.tsx
app/components/Deck/Deck.tsx
app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/NoQuestionsCard/constants.tsx
app/daily-deck/page.tsx
stories/Deck.stories.tsx
stories/NoQuestionsCard.stories.tsx

Fixed final screen text on daily deck.

final screen daily deck fix

---

app/providers/RevealProvider.tsx

Ticket: https://app.clickup.com/t/86bz05wfz

feat: add reveal modal info

---

app/components/Navbar/Navbar.tsx
app/components/QuickViewProfile/QuickViewProfile.tsx

https://app.clickup.com/t/86bz0yzkq
https://app.clickup.com/t/86bz0yv1r

minor fixes

---

app/providers/RevealProvider.tsx

- Description:
Fixed the problems given in: 
https://app.clickup.com/t/86byrxd0b

fix: reveal sheet close problem and confetti

---

app/application/answer/reveal/[questionId]/page.tsx
app/components/AnsweredQuestionShow/AnsweredQuestionShow.tsx
app/components/Button/Button.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx
app/components/QuestionCard/QuestionCard.tsx
app/components/QuestionCardContent/QuestionCardContent.tsx
app/components/RadioInput/RadioInput.tsx
app/queries/question.ts
stories/QuestionCard.stories.tsx
stories/RadioInput.stories.tsx

https://app.clickup.com/t/86bz05w88

feat: reveal-page-when-user-reveals-after-expiration

---

app/login/page.tsx
app/screens/LoginScreens/ExistingUserScreen.tsx
app/screens/LoginScreens/LoginScreen.tsx

https://app.clickup.com/t/86bz0zuj6

fix daily deck label on login

---

app/components/TransactionsTable/TransactionRow/TransactionRow.tsx
app/components/TransactionsTable/TransactionRow/constants.ts

https://app.clickup.com/t/86bz0yvb5

history label fixes

---

app/queries/deck.ts

fix login page redirect

---

app/application/layout.tsx
app/utils/solana.ts

- Description:
- ClickUp links: https://app.clickup.com/t/86bz0yw82

fix bonk balance

---

app/components/Deck/Deck.tsx
app/components/Question/Question.tsx
app/components/QuestionAction/QuestionAction.tsx
app/components/QuestionCardContent/QuestionCardContent.tsx
app/screens/TutorialScreens/BinaryQuestionScreen/BinaryQuestionScreen.tsx
app/screens/TutorialScreens/MultipleChoiceScreen/MultipleChoiceScreen.tsx

- Description: fix 2nd order slider
- ClickUp links: https://app.clickup.com/t/86bz0zrbw

fix 2nd order slider

---

app/components/MobileChromeDetector/MobileChromeDetector.tsx
app/layout.tsx

https://app.clickup.com/t/86bz14tae

add mobile chrome detector

---

app/components/DeckForm/DeckForm.tsx

- Description:
- ClickUp links: https://app.clickup.com/t/86bz14qam

make deck active by default in form

---

app/queries/home.ts

- Description: 
- ClickUp links: https://app.clickup.com/t/86bz14ycv

fix cards chomped count

---

app/application/answer/deck/[id]/page.tsx
app/application/answer/question/[id]/page.tsx

try to fix with revalidate = 0

---

app/actions/answer.ts
app/queries/deck.ts

https://app.clickup.com/t/86bz14rj3

fix: deck reveal

---

app/components/QuestionAction/QuestionAction.tsx
app/queries/home.ts

fix binary slider and cards chomped

---

app/screens/TutorialScreens/RevealScreen/RevealScreen.tsx

fix: tutorial reveal copy

---

app/screens/TutorialScreens/RevealScreen/RevealScreen.tsx

- Description:
Tutorial section revealing text update

fix: tutorial text

---

app/actions/answer.ts
app/application/answer/deck/[id]/page.tsx
app/queries/deck.ts

release: drip v4

---

app/screens/TutorialScreens/BinaryQuestionScreen/BinaryQuestionScreen.tsx

fix: typo in sbf question

---

README.md
app/screens/LoginScreens/constants.tsx

fix: DRiP typos

---

app/components/QuestionCard/QuestionCard.tsx
app/screens/TutorialScreens/BinaryQuestionScreen/BinaryQuestionScreen.tsx

https://app.clickup.com/t/86bz14yy7

z index fix

---

app/components/HomeFeedDeckExpiringSection/HomeFeedDeckExpiringSection.tsx
app/components/HomeFeedEmptyQuestionCard/HomeFeedEmptyQuestionCard.tsx
app/components/HomeFeedReadyToRevealSection/HomeFeedReadyToRevealSection.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx
stories/HomeFeedEmptyQuestionCard.stories.tsx

https://app.clickup.com/t/86bz1tg3v

copy text fix

---

app/application/answer/reveal/[questionId]/page.tsx
app/components/AnsweredQuestionShow/AnsweredQuestionShow.tsx
app/components/ClaimButton/ClaimButton.tsx

https://app.clickup.com/t/86bz0yjkz

fix: duplicate claim button fix

---

app/components/AnsweredQuestionShow/AnsweredQuestionShow.tsx
app/components/HomeFeedQuestionCard/HomeFeedQuestionCard.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx

https://app.clickup.com/t/86bz2j6x7

add reveal for view

---

app/components/HomeFeedCardsCarousel/HomeFeedCardsCarousel.tsx

https://app.clickup.com/t/86bz2jnm0

slider fix

---

app/components/DashboardUserStats/StatsChip.tsx
app/components/InfoBoxes/Home/DailyDeckStreak.tsx
app/components/InfoBoxes/Home/TotalCardsChomped.tsx

https://app.clickup.com/t/86bz2a0ze

height fixes

---

app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/NoQuestionsCard/constants.tsx

- Description:
- ClickUp links: https://app.clickup.com/t/86bz1mtdd
I have aligned the text to left, and made the component to take full height when it is for answer page.

fix: answer page, no question card component.

---

app/providers/RevealProvider.tsx

https://app.clickup.com/t/86bz37p2j

cancel button fix

---

app/application/answer/reveal/[questionId]/page.tsx

fix reveal page when not revealed

---

app/components/ClaimButton/ClaimButton.tsx
app/components/InfoBoxes/RevealPage/RewardInfoBox.tsx
app/components/RewardShow/RewardShow.tsx
app/components/TransactionProfile/TransactionProfile.tsx

floor bonk amount

---

app/providers/RevealProvider.tsx

- Description:
- ClickUp links: https://app.clickup.com/t/86bz37nzf
In this pr I have resolved the problem with confetti firing after revealing. It does not fires confetti anymore.

fix: confetti firing after reveal

---

app/actions/chompResult.ts
app/actions/claim.ts
app/components/ClaimFeedQuestionCard/ClaimFeedQuestionCard.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx
app/components/RevealFeedQuestionCard/RevealFeedQuestionCard.tsx
app/providers/RevealProvider.tsx
app/utils/mutex.ts
package.json
yarn.lock

mutex and invalidate genesis nft reveal state

---

app/layout.tsx

- Description:
Fix: order of components

fix: component order

---

app/layout.tsx
app/utils/algo.ts

release: DRiP reveal v2

---

app/queries/home.ts

https://app.clickup.com/t/86bz28025

expiring soon fix

---

app/components/AnsweredQuestionShow/AnsweredQuestionShow.tsx

add placeholders

---

app/application/answer/reveal/[questionId]/page.tsx
app/constants/solscan.ts

https://app.clickup.com/t/86bz37t0u

add transaction link

---

app/actions/streak.ts

https://app.clickup.com/t/86bz29d8y

streak fix

---

app/components/NoQuestionsCard/constants.tsx

- Description:
- ClickUp links: https://app.clickup.com/t/86bz29g2g
In this pr I have made the connection for link items that were missing redirection.

fix: redirection links connection

---

app/components/Question/Question.tsx
app/components/QuestionCard/QuestionCard.tsx
stories/Question.stories.tsx

- Description:
Issue with question actions
https://app.clickup.com/t/86bz4anxe
Have unanswered deck question and open on mobile resolution to confirm fix. Or use storybook Question\Cramped sample.

Patch screen for mobile

---

app/actions/answer.ts
app/actions/fungible-asset.ts
app/queries/user.ts
app/screens/TutorialScreens/MultipleChoiceScreen/MultipleChoiceScreen.tsx
app/screens/TutorialScreens/RevealScreen/RevealScreen.tsx
app/screens/TutorialScreens/TutorialFlowScreens/TutorialFlowScreens.tsx
app/tutorial/page.tsx
prisma/migrations/20240611114835_add_tutorial_completed_at/migration.sql
prisma/schema.prisma

https://app.clickup.com/t/86bz50nba

fix: tutorial points

---

app/components/Icons/ToastIcons/SpinnerIcon.tsx
app/providers/RevealProvider.tsx
app/providers/ToastProvider.tsx

- Description:
- ClickUp links: https://app.clickup.com/t/86bz45b8c
In this pr I have resolved the problem with promise toasts not closing when clicked on close icon.

fix: promise toasts not closing problem

---

app/actions/chompResult.ts
app/actions/used-nft-genesis.ts
app/components/DeckDetails/DeckDetails.tsx
app/components/FeedQuestionCard/FeedQuestionCard.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx
app/components/RevealFeedQuestionCard/RevealFeedQuestionCard.tsx
app/providers/RevealProvider.tsx
app/queries/home.ts
prisma/migrations/20240612114300_add_transaction_status/migration.sql
prisma/schema.prisma

Ticket: https://app.clickup.com/t/86bz37p5g
Reveal all is temporarily commented because we need to test it more, and change the logic there beacuse of new chagnes I made. I will add ticket for that.
@AnteVuletic please take a look at this pr 😄

fix: hard refresh while burning bonk

---

app/application/answer/reveal/[questionId]/page.tsx

https://app.clickup.com/t/86bz6ezvu

reveal check fix

---

scripts/CreateDeckWithAnswers.ts

- Description:
- ClickUp links: https://app.clickup.com/t/86bz6c4nm
In this pr I have created a typescript function where it creates a deck and injects 10 random answers inside. You have to use run the script with `npx ts-node createDeckWithAnswers.ts`. Also make sure your environment variables exist.

feat: script to create a deck with answers

---

app/queries/question.ts
app/utils/algo.ts

https://app.clickup.com/t/86bz7tg59

objective questions fix

---

app/components/Sheet/Sheet.tsx

https://app.clickup.com/t/86bz82p6q

dimmed screen fix

---

app/components/HistoryFeedRowCard/HistoryFeedRowCard.tsx
app/queries/history.ts

- Description:
Remapping states for history
https://app.clickup.com/t/86bz6b128

Add fixes to deck history

---

app/application/answer/frame/page.tsx
app/components/ClaimFeedQuestionCard/ClaimFeedQuestionCard.tsx
app/components/DeckDetails/DeckDetails.tsx
app/components/History/History.tsx
app/components/HomeFeedDeckExpiringSection/HomeFeedDeckExpiringSection.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx
app/components/LinkProgressBar/LinkProgressBar.tsx
app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/Question/Question.tsx
app/components/RevealFeedQuestionCard/RevealFeedQuestionCard.tsx
app/layout.tsx
package.json
yarn.lock

Added routing progress bar at the top because navigating between pages sometimes can be slow.
https://github.com/gator-labs/chomp/assets/104349866/1053132a-ef5c-47f4-8e51-bbc98f1ad979

added LinkProgressBar

---

app/application/answer/reveal/[questionId]/page.tsx

https://app.clickup.com/t/86bz6xuw7

questions naming fix

---

app/components/QuestionAction/QuestionAction.tsx
app/components/Tooltip/Tooltip.tsx
app/screens/TutorialScreens/BinaryQuestionScreen/BinaryQuestionScreen.tsx
app/screens/TutorialScreens/BinaryQuestionScreen/constants.ts
app/screens/TutorialScreens/MultipleChoiceScreen/MultipleChoiceScreen.tsx
app/screens/TutorialScreens/MultipleChoiceScreen/constants.ts
app/screens/TutorialScreens/RevealScreen/RevealScreen.tsx

- Description:
- ClickUp links: https://app.clickup.com/t/86bz0zx4j
In this pr I have made UI fixes for tutorial page.

Fix/tutorial UI

---

app/utils/algo.ts
app/utils/array.ts

https://app.clickup.com/t/86bz3q6d1

second order estimates fix

---

app/components/HistoryFeedRowCard/HistoryFeedRowCard.tsx

https://app.clickup.com/t/86bza3rgg
I tested it now and it works fine. Probably some of the fixes that were merged into the prod resolved that problem. So I just uncommented code.
https://github.com/gator-labs/chomp/assets/104349866/7f3460df-1e2d-4bcb-9315-d7db797ba236

open reveal question for profile page

---

app/application/layout.tsx
app/providers/ConfettiProvider.tsx
app/tutorial/page.tsx

https://app.clickup.com/t/86bz82p6q

fix: confetti

---

app/components/Button/Button.tsx
app/components/PrimarySlider/PrimarySliderV2.tsx
app/components/QuestionAction/QuestionAction.tsx
app/components/TrueFalseScale/TrueFalseScale.tsx
tailwind.config.ts

ticket: https://app.clickup.com/t/86bz94ryq

fix slider thumb

---

app/components/DeckDetailsFeedRowCard/DeckDetailsFeedRowCard.tsx
app/components/SeeFeedQuestionCard/SeeFeedQuestionCard.tsx
app/utils/question.ts

Ticket: https://app.clickup.com/t/86bzargu2

Card Label Fix

---

app/providers/ToastProvider.tsx

https://app.clickup.com/t/86bz8tdyr

fix toast not closing

---

app/actions/answer.ts
app/application/answer/deck/[id]/page.tsx
app/application/answer/reveal/[questionId]/page.tsx
app/components/QuestionAction/QuestionAction.tsx
app/queries/deck.ts
app/queries/question.ts
app/utils/algo.ts
package.json
scripts/objective-multiple-choice-questions.ts
scripts/utils.ts
tsconfig.scripts.json

https://app.clickup.com/t/86bzbg43e
https://app.clickup.com/t/86bzbg66w
https://app.clickup.com/t/86bzbfz7f

FEATURE: MC Objective Questions

---

app/queries/deck.ts

https://app.clickup.com/t/86bzbg7ny

sorted decks in admin page

---

app/utils/solana.ts

https://app.clickup.com/t/86bzcmxbt

add priority fee when burning bonk

---

app/components/ClaimButton/ClaimButton.tsx
app/hooks/useCopyToClipboard.ts
app/hooks/useCurrentUrl.ts

https://app.clickup.com/t/86bzdnnqj

add share button

---

app/components/Modal/Modal.tsx
app/components/QuestionAnswerPreview/QuestionAnswerPreview.tsx
app/components/QuestionCard/QuestionCard.tsx

https://app.clickup.com/t/86bz87zvq

add preview image

---

app/actions/answer.ts
app/components/Deck/Deck.tsx
app/components/Question/Question.tsx
app/components/QuestionAction/QuestionAction.tsx

https://app.clickup.com/t/86bzc5d3u

dynamic second order option

---

app/application/profile/dashboard/page.tsx
app/application/profile/layout.tsx
app/application/profile/leaderboard/campaign/[id]/page.tsx
app/components/ProfileNavigation/ProfileNavigation.tsx
app/components/ProfileNavigation/constants.ts
app/queries/campaign.ts
next.config.js

https://app.clickup.com/t/86bzddw5z

add campaign sort and profile navigation

---

app/components/Deck/Deck.tsx
app/components/Question/Question.tsx
app/hooks/useRandom.ts

https://app.clickup.com/t/86bzc5d3u

fix: binary percentage selection

---

app/components/Leaderboard/Leaderboard.tsx

https://app.clickup.com/t/86bzjmfed

add missing ranking text

---

app/components/History/TotalRewardsClaimAll/TotalRewardsClaimAll.tsx

- Description:
- 
- https://app.clickup.com/t/86bzm6apa

Renamed label

---

app/application/answer/deck/[id]/page.tsx
app/components/Deck/Deck.tsx
app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/NoQuestionsCard/constants.tsx
app/screens/DailyDeckScreen/DailyDeckScreen.tsx
stories/Deck.stories.tsx
stories/NoQuestionsCard.stories.tsx

https://app.clickup.com/t/86bzh27y6

add next deck button

---

app/components/Deck/Deck.tsx
app/hooks/useRandom.ts

https://app.clickup.com/t/86bzne7q1

Application error fix - PROD

---

app/components/HistoryFeed/HistoryFeed.tsx

- Description:
- Fixed deck list scroll
- https://app.clickup.com/t/86bzn3c8z
- 
https://github.com/user-attachments/assets/d9bfda08-5982-4219-8676-97d19f453cbe

Fixed deck list scroll

---

app/actions/fungible-asset.ts
app/components/HistoryFeed/HistoryFeed.tsx
app/components/HomeFeedDeckCard/HomeFeedDeckCard.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx
app/components/QuickViewProfile/QuickViewProfile.tsx
app/components/Spinner/Spinner.tsx
app/queries/home.ts

release: july 22, 2024 v2

---

app/schemas/profile.ts

- Description:
- Removed validation from last name. Right now last name is not required filed.
- 

Remove validation for lastName as a required field from profileSchema

---

.env.example
app/actions/jwt.ts

Impersonate another user for debugging user failures.

feat: override userId

---

app/components/LeaderboardRanking/LeaderboardRanking.tsx

username fix

---

app/components/Bot/Bot.tsx
app/interfaces/user.ts
app/queries/bot.ts

- Description:
Sync telegram user data having random ID with dynamic ID from miniapp + wallet
https://app.clickup.com/t/86bzumqgw
Verify data through db

[PROD-67] feat: update user record with dynamic

---

app/actions/answer.ts
app/components/Deck/Deck.tsx
app/components/QuestionCard/QuestionCard.tsx

https://app.clickup.com/t/86bzkrcfx

has viewed but not submitted fix

---

app/_reactQuery/useInfiniteQuestionsHistory.ts
app/actions/claim.ts
app/components/ClaimButton/ClaimButton.tsx
app/components/History/PotentialRewardsRevealAll/PotentialRewardsRevealAll.tsx
app/components/History/TotalRewardsClaimAll/TotalRewardsClaimAll.tsx
app/components/QuestionRowCard/QuestionRowCard.tsx
app/components/RewardShow/RewardShow.tsx
yarn.lock

https://app.clickup.com/t/86bztxaxq

history update fix

---

app/components/Bot/Bot.tsx
app/components/BotRevealClaim/BotRevealClaim.tsx

- Description:
Handle user store request efficiently
feat: copy clipboard on address
https://app.clickup.com/t/86bzumqgw
https://app.clickup.com/t/86bzjfvgh
Stop infinite request and handle user store properly

fix: resolve infinite request on reload

---

app/components/History/TotalRewardsClaimAll/TotalRewardsClaimAll.tsx
app/providers/ToastProvider.tsx

https://app.clickup.com/t/86bztfvjn

promise toast fix

---

app/components/Bot/Bot.tsx
app/queries/bot.ts

- Description:
Prevent users from registering multiple email addresses
- Linear link:
https://linear.app/gator/issue/PROD-72/prevent-user-from-registering-multiple-email-addresses
No more multiple email login allowed, the user will have to login through the same email always

PROD-72 Handle multiple email login 

---

app/components/MobileChromeDetector/MobileChromeDetector.tsx

- Description:
Fix browser warning toast in miniapp
- Linear link:
https://linear.app/gator/issue/PROD-70/prevent-browser-warning-from-showing-up-in-miniapp
Stop browser warning toast in miniapp

PROD-70 Prevent browser toast in miniapp

---

app/api/question/reveal/route.ts
app/components/Bot/Bot.tsx
app/components/Bot/ClaimedQuestions/ClaimedQuestions.tsx
app/components/RevealQuestionsFeed/RevealQuestionsFeed.tsx
app/components/SkeletonCard/SkeletonCard.tsx
app/queries/bot/processBurnClaim.ts

- Description: Fixed balance issue and added skeleton for reveal cards
- Linear link: https://linear.app/gator/issue/PROD-75/fix-reveal
Show loading skeleton before reveals are loaded
Should not need to refresh page for balances to load before reveal
Turn off Turnkey on refactoring-dynamic branch

PROD-75 Fix reveal

---

app/components/ActiveIndicator/ActiveIndicator.tsx

- Description:
- Indicator was positioned behind Champaign image 
- https://app.clickup.com/t/86bzv6c1v

Fixed wrong z-index

---

app/components/DeckDetails/DeckDetails.tsx
app/components/History/PotentialRewardsRevealAll/PotentialRewardsRevealAll.tsx
app/components/History/TotalRewardsClaimAll/TotalRewardsClaimAll.tsx
app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx
app/components/QuestionRowCard/QuestionRowCard.tsx
app/components/RevealFeedQuestionCard/RevealFeedQuestionCard.tsx
app/hooks/useReveal.ts
app/providers/RevealProvider.tsx
app/queries/history.ts
prisma/migrations/20240515172459_add_streak_and_time_to_answer/migration.sql
prisma/migrations/20240808164833_chomp_res_unique_constraint/migration.sql
prisma/schema.prisma

https://app.clickup.com/t/86bzvway8

fix: reveal all

---

app/actions/deck/deck.ts
app/components/DeckForm/DeckForm.tsx
app/schemas/deck.ts

https://app.clickup.com/t/86bzry05p

add image upload

---

app/components/Leaderboard/Leaderboard.tsx
app/components/Marquee/Marquee.tsx
app/hooks/useIsOverflowing.ts
package.json
yarn.lock

Ticket: https://linear.app/gator/issue/PROD-116/campaign-scrolling-name

PROD-116 campaign-scrolling-name

---

app/components/HomeFeedRevealedQuestionsSection/HomeFeedRevealedQuestionsSection.tsx
app/queries/home.ts

Ticket: https://linear.app/gator/issue/PROD-113/reveal-most-recent-cards-first

PROD-113 reveal-most-recent-cards-first

---

app/components/TransactionProfile/TransactionProfile.tsx

Ticket: https://linear.app/gator/issue/PROD-114/bug-slow-loading-when-following-deep-profile-link

PROD-114 bug-slow-loading-when-following-deep-profile-link

---

sentry.client.config.ts

- Description
Disable masking of text and media to allow tracing errors efficiently 
Sentry error replay would be unmasked
NA

PROD-211 Update Sentry Config

---

scripts/objective-multiple-choice-questions.ts

fix: mc-obj script

---

app/actions/profile.ts
app/components/ProfileForm/ProfileForm.tsx
app/constants/images.ts
app/schemas/common/imageSchema.ts

Link to the Linear https://linear.app/gator/issue/PROD-80/first-pass-on-profile-page
- Description
- UI and content updates. Added possibility to remove image (sets our default avatar image) on click
New profile setting page

PROD-80 updated profile page

---

app/actions/claim.ts
app/components/RevealFeedQuestionCard/RevealFeedQuestionCard.tsx
app/utils/isSameUrl.ts

- Description
Go straight to answer page after burning BONK
Chompy animation b/w answer page redirect.
[Loom Recording](https://www.loom.com/share/0767b0042ac34dcc9bf0383256098851)

PROD-182 Update/answer page redirect

---

app/actions/deck/deck.ts
app/application/answer/deck/[id]/page.tsx
app/components/DeckForm/DeckForm.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/components/PreviewDeckCard/index.ts
app/components/QuestionCard/QuestionCard.tsx
app/components/Stepper/Stepper.tsx
app/queries/deck.ts
app/schemas/deck.ts
app/screens/DeckScreens/DeckScreen.tsx
prisma/migrations/20240830114551_add_deck_info_columns/migration.sql
prisma/schema.prisma
tailwind.config.ts

** NOTE **
Need to update buttons when we implement them.

PROD-194/deckinfo-card-hi-fi-design-pass & PROD-160/create-deckinfo-card

---

app/api/mixpanel/route.ts
app/constants/mixpanel.ts
app/providers/DynamicProvider.tsx

- Description
Mixpanel event in the login flow. 
Double check login events on mixpanel
No ui changes.

PROD-224: Mixpanel events and updates for login

---

app/actions/answer.ts
app/actions/chompResult.ts
app/actions/claim.ts
app/hooks/useReveal.ts
app/providers/DynamicProvider.tsx
app/utils/error.ts

- Description
Handle exceptions via Sentry in more actions and upgrade the current exception
Try to break something in login, reveal, burn or claim
NA

PROD-222 Add more sentry errors

---

app/actions/answer.ts
app/components/Deck/Deck.tsx
prisma/migrations/20240905163201_add_skipped_status_to_question_answer/migration.sql
prisma/schema.prisma

Link to the task https://linear.app/gator/issue/PROD-159/create-skip-question-functionality
- Description
- Added skip functionalities. If user selects skip option while answering the question, we'll mark that question as "Skipped" just like we do for time out, submit and view.
-

Prod 159/skip question

---

app/components/Deck/Deck.tsx

- Description
Skip button was mistakenly removed from Deck.tsx. 
Skip button on deck.

fix: added skip button again.

---

app/utils/sentry.ts

- Description
Filter Sentry Error: Talisman extension has not been configured yet. Please continue with onboarding.
Prevent unnecessary flags
NA

PROD-260 Filter Sentry Error

---

app/components/DailyDeckRedirect/DailyDeckRedirect.tsx

- Description
- before checking for daily deck I've added condition that checks if user has deck in its url 

PROD-292 added redirect check for direct deck link

---

app/campaigns/[id]/page.tsx
app/components/CampaignDeckCard/CampaignDeckCard.tsx
app/hooks/useReveal.ts
app/layout.tsx
app/providers/ClaimProvider.tsx
app/providers/RevealProvider.tsx
app/queries/campaign.ts

@Yihwan  I connected just functionality to reveal and claim. Still waiting for new dialog to be merged. 
One question, where should "View results" redirect user?

PROD-256/implement-revealclaim-dialog-from-campaigndetail-page

---

app/application/decks/[id]/page.tsx
app/components/ComingSoonDeck/ComingSoonDeck.tsx
app/components/CommingSoonDeck/CommingSoonDeck.tsx
app/components/Icons/BackIconOutline.tsx
app/components/Icons/HomeIconOutline.tsx
app/queries/deck.ts

- Description
Comming soon page will come for deck where activeDate is in the future.
Comming soon page for upcoming deck.

feat: coming soon page for upcoming deck

---

app/components/HomeFeedDeckCard/HomeFeedDeckCard.tsx

Fixed deck url

---

package.json
scripts/objective-binary-questions.ts

For testing purposes. `yarn dev:binary-obj`. Copied from multiple choice script.

feat: script for gen binary question

---

app/providers/RevealProvider.tsx

- Description
- Found out minor styling issue bug in reveal modal -> insufficient funds

Fixed styling in reveal modal

---

app/components/DeckForm/DeckForm.tsx
app/components/DeckList/Action.tsx
app/components/DeckList/Columns.tsx
app/queries/campaign.ts

- Description
- Link to the Linear https://linear.app/gator/issue/PROD-294/admin-panel-admin-changes

PROD-294 admin panel updates

---

app/components/QuestionAction/constants.tsx

PROD-317 fixed color

---

app/application/decks/[id]/page.tsx

- Description
Fixed ternary issue
Properly rendering required component based on the condition.

fixed ternary issue

---

.github/workflows/backup.yml

Related to: https://linear.app/gator/issue/PROD-285/improve-db-restore

feat: make backups hourly

---

app/campaigns/[id]/page.tsx
app/campaigns/page.tsx
app/components/CampaignsHeader/CampaignsHeader.tsx

- Description
1. Added route back to campaign on specific campaign page
2. Udated campaign image as fallback image and set default to deck image.
1. Redirecting back to campaigns from /campaigns/{campaignsId}
2. Verifying decks images on /campaigns/{campaignsId}

PROD-295: campaign decks cleanup

---

app/campaigns/[id]/page.tsx
app/components/CampaignDeckCard/CampaignDeckCard.tsx
app/components/ComingSoonDeck/ComingSoonDeck.tsx
app/components/LoginPopUp/LoginPopUp.tsx
app/queries/campaign.ts
app/screens/LoginScreens/LoadingScreen.tsx

@marvinmarnold @Yihwan I know that it says in ticket that after login it should redirect a user to deck screen. But there is some problem with nextjs navigation where I lost already a lot of time. So I would like to move on to share functionality and leave that for later.

PROD-257/create-connect-wallet-state-on-campaigndetails

---

app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/screens/DeckScreens/DeckScreen.tsx

- Description
Updated deckinfo button to shadcn and screen size
Updated ui and functional go back button.

PROD-296/deck-info-style-changes

---

app/components/DeckForm/DeckForm.tsx

PROD-329 none campaign state

---

app/application/decks/[id]/page.tsx
app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/NoQuestionsCard/constants.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/daily-deck/page.tsx
app/queries/campaign.ts
app/queries/deck.ts
app/queries/home.ts
app/screens/DailyDeckScreen/DailyDeckScreen.tsx
app/screens/DeckScreens/DeckScreen.tsx
styles/globals.css

- Description
Updates in deck completion screen ui
1.Share button functionality 
2.Next Deck functionality 
Next Deck + arrow icon: next deck in campaign (if one exists) else
Next Deck + arrow icon: next any active deck  (if one exists) else
Go home (if no active deck exists)

PROD-299/deck-completion-screen

---

app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/components/Stepper/Stepper.tsx
app/components/ui/button.tsx
app/hooks/useReveal.ts
app/providers/RevealProvider.tsx
app/screens/DeckScreens/DeckScreen.tsx

- Description
Updated deck info design
New deck info card design

Prod 326: deckinfo hi fi

---

app/components/ui/button.tsx
app/hooks/useReveal.ts
app/providers/RevealProvider.tsx

- Description
Added loading functionality to shadcn button 
Loading functionality impented on reveal button click.
https://github.com/user-attachments/assets/f638702c-a36a-40f0-806e-71da61a9c4a2

PROD-279/button-loading-spinner-disabled-functionality

---

app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/constants/mixpanel.ts

- Description
Add mixpanel event for share of deck
Track share and earn event on mixpanel
NA

feat: taskon mixpanel event

---

app/components/ErrorBoundary/ErrorBoundary.tsx
lib/urls.ts

PROD-334: push people to refresh on error

---

app/components/CampaignDeckCard/CampaignDeckCard.tsx

https://gator-labs.slack.com/archives/C06054PPNSY/p1726886180317439
- Remove login popup
- Redirect after login

fix: disable login popup

---

app/actions/leaderboard.ts

- Description
- Link to the Linear https://linear.app/gator/issue/PROD-338/enigma-leaderboard-broken

PROD-338 fixed broken champaign leaderboard

---

app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/components/QuestionAnswerPreview/QuestionAnswerPreview.tsx
app/components/QuestionCard/QuestionCard.tsx
styles/globals.css

- Description
- According to our meeting @marvinmarnold I've removed global config for QuestionCard. Removed min-h from 480px to 350px
https://github.com/user-attachments/assets/be8f2202-17c3-4255-9a5d-2edbe816ab9e

PROD-330 updated min-h property for question cards

---

app/_reactQuery/useInfiniteQuestionsHistory.ts
app/components/RevealDeck/RevealDeck.tsx

PROD-339 fixed deck history cache

---

app/components/Deck/Deck.tsx

- Description
Skip will be disabled until the previous question skip question query is executed
Multiple clicks will not work in skip question until previous query is executed

PROD-335: disable skip question until processing

---

app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/components/QuestionCard/QuestionCard.tsx
app/screens/DeckScreens/DeckScreen.tsx

- Description
Changes no question card height to a fix height 350px with overflow scroll.

PROD-345: deck completion height issue.

---

__tests__/rewards-mc-obj.test.ts
app/queries/getPriorityFeeEstimate.ts

- Description
Fix the priority fee estimate params issue in `getPriorityFeeEstimate` RPC method
Test reveal
NA

PROD-367: Update priority fee params

---

app/components/LoginPopUp/LoginPopUp.tsx
app/components/StackDeckCard/StackDeckCard.tsx
app/stacks/[id]/page.tsx

The problem was in useEffect, there was a missing guard if (!isOpen) return;
Because without this, useEffect was run in all components and now is run only when popup is opened in specific component.

PROD-341/fix-login-popup-from-campaigns

---

app/actions/claim.ts

- Description
Fixed undefined value in solscan link and prevent Sentry error when getBonkBalance returns 0
N/A
N/A

Prod 356: treasury balance buggy

---

__tests__/actions/deck/deck-editDeck.test.ts
app/actions/deck/deck.ts

Fixed issue with editDeck test fail.

fix: editDeck test fail issue

---

app/application/answer/reveal/[questionId]/page.tsx
app/components/BestAnswerBinary/BestAnswerBinary.tsx
app/components/BestAnswerMultipleChoice/BestAnswerMultipleChoice.tsx
stories/BestAnswerBinary.stories.tsx

- Description
- Link to the linear task: https://linear.app/gator/issue/PROD-369/remove-thumbs-up-and-down-icon-from-answer-reveal-page. After long discussions and changes, decision has been made to just remove icons without any other update.

Prod 369 remove like dislike icons

---

__tests__/actions/get_alltime-leaderboard.test.ts
jest.config.js

- Description
Timeout of jest test

jest test timeout 20s

---

app/components/NoQuestionsCard/NoQuestionsCard.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/components/QuestionCard/QuestionCard.tsx
app/components/QuestionCardLayout/QuestionCardLayout.tsx

- Description
Added a common layout for question related cards instead of using same style and images in multiple places.
There should not be any changes in the UI
N/A

PROD-397: Refactor QuestionCard, PreviewCard, and NoQuestionsCard

---

README.md
scripts/restore-database.ts

- Description
RFC - Restore database 
Add step by step instructions to restore database from backup file easily
Try restoring local db
NA

PROD-285 Add comments for restore database

---

app/components/AnswerResult/AnswerResult.tsx
app/components/PrimarySlider/PrimarySlider.tsx
app/components/RadioInput/RadioInput.tsx

- Description
Flexible question options height in QuestionCard
Verify deck 275

style(fix): mc options height

---

.husky/pre-commit
app/actions/leaderboard.ts
app/components/DeckList/Columns.tsx
app/components/DeckList/DeckList.tsx
app/components/Leaderboard/Leaderboard.tsx

- Description
Update husky config to check-format and break if formatting issues to include formatting in the same commit. 
N/A

fix: added check-format to disable auto formatting

---

app/actions/claim.ts
app/actions/leaderboard.ts
app/components/ClaimButton/ClaimButton.tsx
app/components/ClaimButton/contants.tsx
app/components/DeckList/Columns.tsx
app/components/DeckList/DeckList.tsx
app/components/Leaderboard/Leaderboard.tsx
app/providers/ToastProvider.tsx

- Description
Previously if claim fails user isn't able to claim again but his bonk is already burned after this change user will be able do claim again incase it fails.
Error through if sendBonk failed and not user should be able to claim again if it fails

Prod 422: error recovery failed claim

---

app/components/Bot/Bot.tsx
app/components/Leaderboard/Leaderboard.tsx
app/login/page.tsx
app/providers/RevealProvider.tsx
app/screens/LoginScreens/LoginScreen.tsx

- Description
If a user accesses the PWA from the mini app, they will be automatically logged in to the PWA.
Auto login into PWA if accessed from mini app
N/A

PROD-407: telegram auto login functionality from pwa

---

app/components/QuestionCardLayout/QuestionCardLayout.tsx

- Description
Fixed pulsing scroll bar in question card
https://github.com/user-attachments/assets/aaf0b642-5d7d-4b60-ae3d-9da0d2247657

PROD-451: Add padding bottom in question card

---

app/application/layout.tsx
app/components/Profile/Profile.tsx
app/layout.tsx

Added some null/undefined checks - I observed come crashes locally when a wallet is not installed.

fix: check wallet object is defined before use.

---

.github/workflows/migrations.yml

- Description
Added Workflow to run migration in demo-db on commit push to the demo branch. 
successful migration in demo db on commit push to demo branch
N/A

feat: add migrations for demo DB on commit push

---

app/actions/leaderboard.ts
app/utils/sentry.ts

- Description
This is related to PROD-359, PROD-360, PROD-361. Ignore the errors recording in Sentry
NA
NA

fix: Add dynamic errors in sentry ignore

---

__tests__/queries/history/sql-injection-regression.ts
app/_reactQuery/useInfiniteQuestionsHistory.ts
app/actions/history.ts
app/components/History/History.tsx
app/components/HistoryHeader/HistoryHeader.tsx
app/components/QuestionRowCard/QuestionRowCard.tsx
app/components/RevealDeck/RevealDeck.tsx
app/queries/history.ts

- I introduced bad code when backmerging directly from GH
- Also debugging build issues here: https://github.com/gator-labs/chomp/pull/656

fix: formatting issues

---

app/utils/claim.ts
app/utils/solana.ts

Round fee and compute limit values to nearest int before trying to send tx.
Linear: PROD-489

fix: round tx values to int

---

app/components/QuestionAction/QuestionAction.tsx

- Description
Previously it was possible that user can do multiples clicks while submitting multiple choice question
One entry in fungible transaction log and in mixpanel for multiple choice question answer.
N/A

fix: added disable on multiple choice when submitting

---

app/actions/claim.ts
app/components/Bot/Bot.tsx
app/components/QuestionAction/QuestionAction.tsx
app/hooks/useReveal.ts
app/utils/claim.ts
app/utils/solana.ts

- [fix](https://github.com/gator-labs/chomp/pull/668): prevent multiple submissions for multiple choice 
- [fix](https://github.com/gator-labs/chomp/pull/671): use fresher recent blockhash for reveal and claim

release(hotfix): nov 15, 2024

---

app/actions/claim.ts
app/actions/history.ts
app/api/og/share-claim-all/route.tsx
prisma/migrations/20241125080610_add_indexes_to_chomp_result/migration.sql
prisma/schema.prisma

This fixes the issue. I am working on claim question test but you can merge this so users can claim their questions. @marvinmarnold

PROD-499/fix-claim-when-revealed-with-nft

---

__tests__/actions/get_alltime-leaderboard.test.ts

Resolves an issue introduced with the previous fix that was uncovered by a newly-added database constraint.

PROD-486: Additional fix for flaky all-time test

---

app/actions/chompResult.ts

- Description
Added query to remove fungible transaction before completing the reveal query. 
- Steps to test
Try to reveal and reveal all.

fix: add query to remove old transaction log in reveal

---

app/actions/mysteryBox/open.ts
app/actions/mysteryBox/reveal.ts
components/MysteryBox/MysteryBox.tsx
lib/error.ts
package.json
yarn.lock

Split the opening process into two stages so the UI is more responsive.

PROD-538: Mystery box separate reveal and claim actions

---

yarn.lock

feat: yarn lock update

---

app/components/QuickViewProfile/QuickViewProfile.tsx

PROD-531: Replace chompgames telegram link

---

__tests__/queries/home/deck.test.ts
__tests__/queries/home/get-total-claimed-amount.test.ts
__tests__/queries/home/streak.test.ts
__tests__/utils/date.test.ts

- Description
Fix some flaky tests by adding retry mock
NA
NA

fix: flaky tests

---

package.json
yarn.lock

- Description
Bump **@solana/web3.js** version to `1.95.8` for security reasons raised recently
NA
NA

PROD-540 Upgrade @solana/web3.js dependency

---

__tests__/actions/chompmas-mystery-box.test.ts
lib/mysteryBox.ts

Fixes an issue with Chompmas boxes.

Fix Chompas mystery box

---

package.json
yarn.lock

fix: pinned @solana/web3.js to 1.95.8

---

.env.example
app/actions/question/generateTestQuestion.ts
app/admin/page.tsx
app/components/AdminBinaryQuestionGeneratorForm/AdminBinaryQuestionGeneratorForm.tsx
app/components/AdminMultiChoiceQuestionGeneratorForm/AdminMultiChoiceQuestionGeneratorForm.tsx

- Description
- Link to the task https://linear.app/gator/issue/PROD-539/create-ui-that-runs-devmc-obj-on-staging
https://github.com/user-attachments/assets/b98b1d92-cea6-413c-858e-f04d17dec627

PROD-539 added UI for scripts

---

app/queries/home.ts

Fix streak length lookup for new users (when there are no chomp results yet).

Fix streak length lookup for new users.

---

scripts/addAllowlistUsers.ts

- Description
Filter out empty records from allowlist csv before creating records
Use add allowlist users script
NA

PROD-569: Fix allowlist script ignore empty

---

components/MysteryBox/MysteryBox.tsx

fix: change size for end state

---

app/components/History/PotentialRewardsRevealAll/PotentialRewardsRevealAll.tsx
app/components/RevealFeedQuestionCard/RevealFeedQuestionCard.tsx
app/hooks/useReveal.ts
app/providers/RevealProvider.tsx

This PR will fix the feature where user wasn't able to reveal all with unused nft

fix: allow user to reveall all with unused nft and refactor code

---

app/components/LatestStreakBox/LatestStreakBox.tsx
components/MysteryBox/MysteryBox.tsx

Fix a few mystery box UI issues:
- Re-add streak box click (for mystery boxes) which was removed in a previous commit.
- Show correct button/cursor state while loading.
- Clean up isSubmitting check.

Fix: mystery box tweaks

---

app/actions/mysteryBox/open.ts
app/constants/sentry.ts

fix: flush sentry

---

prisma/migrations/20241126064715_new_mystery_box_schema/migration.sql
prisma/migrations/20241126114219_add_connect_x_and_connect_telegram_to_transaction_log_type/migration.sql

Addressing: https://github.com/gator-labs/chomp/actions/runs/12363271326/job/34504262813

fix: comment migrations done manually

---

prisma/migrations/20241126064715_new_mystery_box_schema/migration.sql
prisma/migrations/20241126114219_add_connect_x_and_connect_telegram_to_transaction_log_type/migration.sql

Follow-up to: https://github.com/gator-labs/chomp/pull/754

fix: back to original migrations after manual resolution

---

.env.example
app/components/LatestStreakBox/LatestStreakBox.tsx

https://github.com/user-attachments/assets/d2adae29-62ce-46cd-84ad-33628ae4a6d5

feat: add animation on text

---

.github/workflows/replica-sync.yml

- Description: Sync most recent DB backup to Neon every hour

build (PROD-576): workflow to sync DB

---

prisma/migrations/20241218180555_address_length_check/migration.sql
scripts/addAllowlistUsers.ts

- Description
Enable check constraint for address property in allowlist table
Try with anomalies data and run the script
NA

PROD-569: Add address length check constraint

---

app/actions/chompResult.ts

Poll transaction method is returning confirmed event the tx fails if user have insufficient bonk and have a unused nft.

remove poll transaction

---

app/components/ShareResult/ShareResult.tsx

- Description
- Reused formatting just like we have on all places where claim amount should be displayed.

PROD-588 fixed claim reward formatting

---

.env.example
app/actions/deck/deck.ts
app/components/DeckForm/DeckForm.tsx
app/schemas/deck.ts
app/schemas/question.ts
prisma/migrations/20241220200651_add_credit_cost_per_question/migration.sql
prisma/schema.prisma

- Description
Add new select input in Deck form to allocate credits to each questions - Credit Flow (Featured flag)
Create a new deck or edit existing deck, you will see Credit Cost property at second last in the form
NA

PROD-550: Credit Cost Per Question Deck Form Admin

---

__tests__/api/process-pending-transaction/route.test.ts
app/actions/chompResult.ts
app/api/process-pending-transaction/route.ts
app/utils/solana.ts
lib/error.ts
prisma/migrations/20241223180534_burn_valid_signature/migration.sql

- Description
This PR will prevent empty string burn tx in database and record in Sentry. It adds a constraint and validate in server actions using bs58 decode if string is valid signature or not
NA
NA

PROD-608: Add valid burn sign constraint

---

app/global-error.tsx
instrumentation.ts
next.config.js
sentry.client.config.ts

- Description
Enable Sentry wizard to record full code trace
NA
NA

PROD-572: Setup sentry wizard

---

__tests__/actions/chompmas-mystery-box.test.ts
__tests__/actions/mystery-box.test.ts

- Description
Ensure dummy data is deleted in test once test is completed to avoid trash data in prod
Run tests
NA

PROD-611: Fix test afterAll 

---

.env.example
__tests__/queries/get-new-mystery-box.test.ts
app/queries/mysteryBox.ts

Mystery box tutorial feature flag

feat: add feature flag

---

docs/temp.sql

build: temp sql file to force migration

---

app/application/answer/page.tsx
app/application/decks/[id]/page.tsx
app/components/DeckScreenAction/DeckScreenAction.tsx
app/queries/deck.ts
app/screens/DeckScreens/DeckScreen.tsx

- Description
Add random credit free deck option in paid deck
Open a credit based deck

PROD-621: Credit free random deck CTA

---

app/application/answer/page.tsx
app/application/decks/[id]/page.tsx
app/components/DeckScreenAction/DeckScreenAction.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/queries/deck.ts
app/screens/DeckScreens/DeckScreen.tsx

- Description
Show the buttons according to credits required and add buy credit drawer
Open a deck

PROD-620: Deck Screen CTA

---

app/application/answer/page.tsx
app/application/decks/[id]/page.tsx
app/application/decks/page.tsx
app/components/DeckScreenAction/DeckScreenAction.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/queries/deck.ts
app/screens/DeckScreens/DeckScreen.tsx
tailwind.config.ts

- Description
Show credist balance on decks with feature flag
Credit balance will be visible before the deck begin if the feature flag is true.

PROD-618: add credit cost to deck

---

app/components/DeckScreenAction/DeckScreenAction.tsx

- Description
Fix the DeckScreen CTA action conditions

fix: credit deck cost condition

---

package.json

Downgrade sharp based on https://github.com/lovell/sharp/issues/3870#issuecomment-1833121113

build: sharp fix

---

components/MysteryBox/MysteryBox.tsx

- Description
Update logic based on box type instead of prize for the box to show proper animation.
Closed green box for new user after user completes or skip the tutorial.

PROD-630: show box animation based on box type

---

app/utils/claim.ts

Using server only make sure that if this is imported in client it will through error.

feat: make send bonk utils server only

---

.github/workflows/migrations.yml

build: allow manual staging migrations

---

lib/mysteryBox.ts

- Description
This will create mysterybox with credits and bonk if credit is present in reward and credit animation will be visible after revealAll event type.
Reveal all and open mystery box to verify 
NA

PROD-627: Enable credits with bonk mystery box

---

app/actions/answer.ts
app/actions/fungible-asset.ts
app/application/answer/page.tsx
app/application/decks/[id]/page.tsx
app/components/BuyCreditsDrawer/BuyCreditsDrawer.tsx
app/components/Deck/Deck.tsx
app/components/DeckScreenAction/DeckScreenAction.tsx
app/components/NotActiveDeck/NotActiveDeck.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/queries/deck.ts
app/screens/DailyDeckScreen/DailyDeckScreen.tsx
app/screens/DeckScreens/DeckScreen.tsx
lib/error.ts
prisma/migrations/20250101103924_premium_question_enum_fatl/migration.sql
prisma/migrations/20250106080253_add_deck_id_question_id_unique_constraint/migration.sql
prisma/schema.prisma
stories/Deck.stories.tsx

- Description
User will be charged for paid decks on per question basis and record will stored in fatl table. This PR also restricts chomping a question if user reaches insufficient in the middle of deck. 
1. Create paid decks
2. Credits should reduce after a paid deck is strated or completed.
3. A Drawer will pop up if user balance reaches low in the middle 
4. Deck will start from begin if user return to home and start again. 
N/A

Prod 582: charge user credit per question

---

yarn.lock

fix: lockfile

---

app/actions/chompResult.ts
app/hooks/useReveal.ts

Encodes transactions that are sent to the backend.
Fixes a bug that prevented successful reveals.

Fix: encode transaction so it can be passed to the backend (fixes reveal)

---

app/hooks/useReveal.ts

This is a WIP branch to accumulate fixes related to reveal issues.

PROD-685: Reveal release fixes

---

app/actions/chompResult.ts
app/schemas/deck.ts

Removed the refinement rule that required at least one correct option in multi-choice questions.

Prod 494: Support subj mcq

---

app/components/StackCard/StackCard.tsx
app/components/StackDeckCard/StackDeckCard.tsx

- Description
Stacks weren't showing the updated data because the data wasn't revalidated.

fix: change link tag to anchor tag for revalidation

---

.github/workflows/test.yml

fix: test case

---

__tests__/queries/stack/get-stack-results.test.ts
vercel.json

- Description
Filename typo and prettier

fix: Cron filename typo

---

__tests__/actions/credits/createChainTx.test.ts
__tests__/api/process-credits/route.test.ts
actions/credits/createChainTx.ts

Fix credits test to take account of configured rate.

PROD-707: Fix credits test to take account of configured rate.

---

__tests__/queries/home/deck.test.ts

Fixes the flaky deck test by discounting data currently in the database.

PROD-669: Fix flaky deck test (alternative approach).

---

app/actions/jwt.ts
app/actions/user.ts
app/admin/layout.tsx
app/admin/users/page.tsx
app/components/AdminTabNavigation/AdminTabNavigation.tsx
app/components/Icons/UserIcon.tsx
app/components/Navigation/Navigation.tsx
app/components/TabNavigation/TabNavigation.tsx
package.json
prisma/migrations/20250124111613_add_new_fatl_log_type/migration.sql
prisma/schema.prisma
scripts/distribute-credit.ts

- Description
Added new user tab with feature of giving user credit with their wallet address. 
Try giving credit to a user id

Prod 649: Give specific user credit admin

---

app/components/ErrorBoundary/ErrorBoundary.tsx
app/layout.tsx
components/ContentUnavailablePage.tsx
lib/jwt.ts

Add enhanced threat level debugging.

Threat level debugging updates

---

app/components/NoDecks/NoDeck.tsx

Add padding to "no decks" message.

PROD-723: Add padding to "no decks" message.

---

app/actions/jwt.ts
app/actions/stack.ts
app/components/FreeDeckFeed/FreeDeckFeed.tsx
app/components/PaidDeckFeed/PaidDeckFeed.tsx
app/components/StackForm/StackForm.tsx
app/queries/home.ts
app/schemas/stack.ts
prisma/migrations/20250127122156_add_new_coulmn_hide_deck_stack/migration.sql
prisma/schema.prisma

- Description
1. Add hideDeckFromHome flag in stacks
2. Hide deck from home if the flag is turn on. 
Only deck with hideDeck from home with value false or null. Should be visible.

Prod 691/enable hide deck new

---

lib/mysteryBox.ts

The mechanism engine returns boxes without BONK sometimes, which makes the current code choke.

Fix: Allow for mystery boxes with no BONK in them (resolves failing tests)

---

app/screens/LoginScreens/LoginScreen.tsx

Go straight to home for existing users, rather than through the "Welcome Back" screen,

PROD-711: Remove welcome back screen

---

app/actions/question/generateTestQuestion.ts
app/components/AdminBinaryQuestionGeneratorForm/AdminBinaryQuestionGeneratorForm.tsx
app/components/AdminMultiChoiceQuestionGeneratorForm/AdminMultiChoiceQuestionGeneratorForm.tsx

Add "credit cost per question" field to admin panel.

PROD-724: Add "credit cost per question" field to admin panel.

---

__tests__/actions/mystery-box.test.ts

Fix: mystery box tests

---

__tests__/queries/answers.ts
app/api/cron/calculate-correct-answers/route.ts
app/queries/answers.ts
vercel.json

Cronjob to calculate correct answers for questions that are ready to reveal.

PROD-730: Cronjob to calculate correct answers for questions that are ready to reveal

---

app/application/history/page.tsx
app/components/ProfileNavigation/constants.ts
app/queries/history.ts
app/utils/history.ts
components/HistoryNew/History.tsx
components/HistoryNew/QuestionCard.tsx
components/RevealDeckNew/RevealDeck.tsx

Wire up new question history page.

Prod 739: Question history page

---

app/actions/answer.ts
app/constants/points.ts
prisma/migrations/20250204122806_add_new_log_type/migration.sql
prisma/schema.prisma

- Description
Change points for answering question based on credit
Answer a free and paid questions both

PROD-733: Enable Points for Paid Questions

---

app/components/BuyCreditsDrawer/BuyCreditsDrawer.tsx
app/components/DeckScreenAction/DeckScreenAction.tsx
app/components/HomeFeedDeckCard/HomeFeedDeckCard.tsx
app/components/HomeFeedVerticalCarousel/HomeFeedVerticalCarousel.tsx
app/components/MysteryBoxReward/MysteryBoxReward.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/components/Profile/Profile.tsx
components/MysteryBox/MysteryBoxHub.tsx

- Don't show SOL amount in engineering format (for tiny numbers).
- Remove Dynamic wallet widget.
- Add pink glowy border to cards on rewards page.
- Change "Free" -> "0 Credits".
- Change "1 Credits" -> "1 Credit".
- Add missing space in info drawer.
- Fixes gradient position on "MYSTERY BOXES" header.

PROD-747: more credits UI fixes

---

app/components/ClaimButton/ClaimButton.tsx

- Description
Even if user won rewards in legacy question then user won't be able to claim now
Try claiming reward for legacy question

PROD-744: Disable legacy question claim button

---

app/api/cron/calculate-correct-answers/route.ts
app/utils/mutex.ts
vercel.json

Reduce correct answer cron interval to 1 minute and protect against multiple concurrent invocations.

PROD-743: reduce wait period to reveal questions

---

app/screens/LoginScreens/SlideshowScreen.tsx

Style: Fix Connect Wallet Alignment

---

__tests__/queries/home/deck.test.ts

Remove second half of old hacky deck test fix.

PROD-755: Fix unanswerable questions on staging

---

app/application/rewards/page.tsx
app/components/MysteryBoxReward/MysteryBoxReward.tsx
components/MysteryBox/MysteryBoxHub.tsx

Refresh mystery box history after opening a box in the hub.

PROD-756: Refresh mystery box history after opening a box in the hub.

---

app/application/answer/page.tsx
app/application/decks/[id]/page.tsx
app/components/BuyCreditsDrawer/BuyCreditsDrawer.tsx
app/components/DashboardUserStats/DashboardUserStats.tsx
app/components/HomeFeedVerticalCarousel/HomeFeedVerticalCarousel.tsx
app/components/InfoDrawer/InfoDrawer.tsx
app/components/NotActiveDeck/NotActiveDeck.tsx
app/components/PreviewDeckCard/PreviewDeckCard.tsx
app/screens/DeckScreens/DeckScreen.tsx
components/MysteryBox/MysteryBoxHub.tsx

- Description
Update preview deck card info copy, home page deck copy, and credit bento box description
Expand info drawer and check CTA

PROD-734: Update info drawer copy

---

app/utils/claim.ts

- Description
Add fixed CU with buffer proportion for receiver ATA creation
Test with new wallet
https://solscan.io/tx/jzLwGSa2VPbvnskGvKNheAKDgxs66qAbQZ9sDtw8dciyk8ySANfkPz726r8kegqnqmd9w62Q6AcbVtppUvFwVBV

PROD-715: Optimize ATA Create Tx

---

app/application/answer/reveal/[questionId]/page.tsx

Fixes 500 errors on answer page (for legacy questions).

PROD-766: Fix 500 errors on answer page

---

__tests__/actions/credits/updateTxStatusConfirm.test.ts
actions/credits/updateTxStatusConfirm.ts
app/constants/solana.ts
lib/credits/initiatePurchase.ts
lib/credits/processTransaction.ts
lib/verifyTransactionInstructions.ts

- Description: Speed up tx processing by only waiting for confirmation and not finalization.
- What are the steps to test that this code is working? Buy credits and time how long it takes. Outputting total elapsed to console. Expect transactions to take about 10s normally. Anything more than 16s should be reported.

feat(PROD-717): wait for confirmation not finalization

---

app/components/HomeFeedDeckCard/HomeFeedDeckCard.tsx

Fix font size for deck rewards according to figma design value
Previous 
Updated

fix font size

---

__tests__/actions/threat-level.test.ts
app/components/MysteryBoxReward/MysteryBoxReward.tsx
components/MysteryBox/MysteryBoxHub.tsx
components/MysteryBoxHub/MysteryBoxHistory.tsx
components/MysteryBoxHub/OpenMysteryBox.tsx

Description:
Added invalidate logic for mysterybox history to update data after mystery box is opened

feat: invalidate mystery box history after box is opened

---

app/actions/mysteryBox/fetchHistory.ts
app/actions/mysteryBox/openMysteryBoxHub.ts
app/actions/mysteryBox/rewardMysteryBoxHub.ts

This fixes the mystery box loop I was seeing. There were a couple of issues: the action was returning unopened boxes, and returning the same box multiple times (for each trigger) - so I think having multiple questions in a box was the problem.

PROD-765: mystery box show as claimable but nothing added to history

---

app/components/MysteryBoxReward/MysteryBoxReward.tsx
components/MysteryBoxHub/MysteryBoxCategoryPill.tsx

- Description
Align the text in mobile view
Go to rewards tab

PROD-789: Fix MB Text Responsive

---

.env.example
app/api/cron/detect-bot-activity/route.ts
app/utils/algo.ts

Mechanism engine configurable URL + error handling.

PROD-787: Mechanism engine configurable URL + error handling

---

app/components/Icons/CoinsIcon.tsx
components/BuyBulkCreditsButton.tsx

Fix "buy more credits" button style.

Fix "buy more credits" button style.

---

app/utils/history.ts
components/HistoryNew/QuestionCardStatus.tsx
package.json
tailwind.config.ts
yarn.lock

PROD-804: Add "View Results in # days" in History Question Card

---

app/components/BuyCreditsDrawer/BuyCreditsDrawer.tsx

Fix the insufficient funds state in Buy Credit Drawer (Deck Preview Card)

PROD-810: Handle low balance in Buy Credits Drawer

---

app/application/answer/reveal/[questionId]/page.tsx

Completely remove rewards button for practice questions.

PROD-817: Completely remove rewards button for practice questions.

---

app/utils/algo.ts

Follow up to https://github.com/gator-labs/chomp/pull/981/files

fix: remove slash from rewards

---

components/MysteryBox/MysteryBox.tsx

Fix credits singular form in mystery box modal.

PROD-823: Fix credits singular form in mystery box modal

---

__tests__/queries/home/deck.test.ts
__tests__/queries/stack/get-stack.test.ts

- Get-stack Test Time
- Home/deck Test time

PROD-808: Fix Flaky Tests

---

__tests__/utils/algo/calculate-correct-answer.test.ts
app/queries/answerPercentageQuery.ts
app/queries/question.ts

Description
Intended behavior is to not include bot response in correct answer  calculation and reward calculation
Solution
Updated answerPercentage query to calculate correct answer data based on non bots user responses.

feat: remove bot response from answer calculation

---

app/components/PreviewDeckCard/PreviewDeckCard.tsx

Include credits in potential rewards in deck preview.

PROD-841: Include credits in potential rewards.

---

app/utils/algo.ts

Update mechanism engine calls to throw an exception instead of using corrupt data.

PROD-828: Throw an exception if the mech engine call fails.

---

__tests__/queries/home/get-next-deck-id-query.test.ts
app/queries/home.ts
app/utils/sendBonk.ts

Hotfix release.
[fix](https://github.com/gator-labs/chomp/pull/1018): 500 error on deck page.

release: Mar 03, 2025

---

__tests__/queries/home/streak.test.ts
app/queries/home.ts

Update streaks to consider credit purchases and mystery box claims.

PROD-855: Update streaks to consider credit purchases and mystery box claims.

---

app/utils/sendBonk.ts

- Failure of Instruction 3: Failed to complete  - https://gator-labs.sentry.io/issues/6334378512/?referrer=Linear
- Computational Budget Exceeded - https://gator-labs.sentry.io/issues/6335504487/?referrer=Linear
Stress test log has been added in Linear comments:  https://linear.app/gator/issue/PROD-867/openmysteryboxhuberror-user-with-id-6be310c4-983b-41e2-a422#comment-51d3531f

PROD-867 and PROD-868: Fix Transaction Simulation Error and CU Budget

---

__tests__/api/detect-bot-activity/route.test.ts
__tests__/lib/bots.test.ts
app/api/cron/detect-bot-activity/route.ts
lib/bot-detector.ts
lib/bots.ts

Fixes the bot detector which was, in fact, not working. Adds tests to prove it now works.

PROD-900: implement bot detector cronjob test

---

app/components/BuyCreditsDrawer/BuyCreditsDrawer.tsx
components/BuyBulkCreditsDrawer.tsx
hooks/useCreditPurchase.ts

Implement timeout during credit purchase.

PROD-811: Implement timeout during credit purchase.

---

__tests__/lib/mysteryBox/create-campaign-mystery-box.test.ts
__tests__/lib/mysteryBox/get-campaigns.test.ts
lib/mysteryBox/createCampaignMysteryBox.ts
prisma/migrations/20250308130515_add_boxtype_to_campaign_mystery_box/migration.sql
prisma/schema.prisma

The box type sent to the mechanism engine depends on the campaign week.

PROD-888: complete campaign mystery box integration

---

__tests__/actions/mystery-box.test.ts
app/components/Stack/Stack.tsx
app/queries/stack.ts
app/stacks/daily-deck/page.tsx
components/CreditPackListItem.tsx
types/stack.ts

- Progress overflow fix in Multiple Option Question

patch: fix stack deck card

---

app/queries/stack.ts

Fix the stack deck state when question is skipped

fix: stack deck state

---

app/queries/answers.ts

PROD-786 updated cron job query

---

__tests__/actions/threat-level.test.ts
__tests__/lib/bots.test.ts
app/components/ErrorBoundary/ErrorBoundary.tsx
app/queries/answerPercentageQuery.ts
lib/bots.ts
lib/jwt.ts
prisma/migrations/20250320112245_add_threatleveldetails_column/migration.sql
prisma/schema.prisma
types/bots.ts

Add new threat level type which results in a distinct error message, vs. the standard bot message.

PROD-929: Implement new engineering threat level type

---

app/utils/sentry.ts

Description: Filter out register destructuring errors

fix(sentry): filter out register destructuring errors

---

app/utils/algo.ts

Only selected answers should be included in data sent to the mechanism engine.
Fixes the first order (correct answer) calculation but doesn't touch the second order calculation as I don't have a way of knowing if the results are correct while the dashboard is also incorrect.

PROD-953: Fix answer calculation for MC questions.

---

app/utils/sendBonk.ts

- Increase base CU limit for ATA creation.
- Increase buffer for all BONK send cases

fix: increase cu limits when sending BONK

---

app/utils/sendBonk.ts
next.config.js

Follow up to: https://github.com/gator-labs/chomp/pull/1070

backmerge: main<-prod hotfix for CU limits

---

package.json
scripts/distribute-credits-csv.ts

Create script to distribute credits from CSV file.

PROD-955: Create script to distribute credits from CSV file.

---

app/components/AnswerResult/AnswerResult.tsx

Fix second order option height to fit content

feat: add height fit for content

---

app/actions/question/generateTestQuestion.ts
app/components/AdminBinaryQuestionGeneratorForm/AdminBinaryQuestionGeneratorForm.tsx
app/components/AdminMultiChoiceQuestionGeneratorForm/AdminMultiChoiceQuestionGeneratorForm.tsx

Allow the creation of multi-question decks from the admin panel on staging.

PROD-972: Allow the creation of multi-question decks from admin panel.

---

__tests__/lib/ask/addToCommunityAskList.test.ts

PROD-1044: Fix ask test: look for existing stack.

---

__tests__/queries/history/getAnsweredDecksForHistory.test.ts
app/queries/history.ts
components/HistoryNew/HistoryDeckCard.tsx
tailwind.config.ts

Description: Show deck with future revealDate in history

Prod 941: Answered unrevealed deck history

---

__tests__/db/triggers/ask-points.test.ts

Add tests for ask DB triggers.

PROD-1031: Add tests for ask DB triggers.

---

__tests__/lib/ask/addToCommunityAskList.test.ts

Fix community ask test: check for multiple ask decks in cleanup.

Fix community ask test: check for multiple ask decks in cleanup.

---

app/application/answer/reveal-new/[questionId]/page.tsx
components/SecondOrderAnswerResult.tsx
components/SecondOrderAnswerResultMultiple.tsx

Use the same layout for binary and MC second order results.

PROD-1061: Use the same layout for binary and MC second order results.

---

prisma/migrations/20250423115953_add_new_feilds_question_table/migration.sql
prisma/schema.prisma

Added new feilds in Question model.

feat: add new feilds in question table

---

app/actions/deck/copyDeck.ts
prisma/migrations/20250422203544_add_question_uuid_column/migration.sql
prisma/schema.prisma

Add `uuid` column to Question table and generate UUIDs for existing questions.

PROD-1046: Add uuid column to Question table.

---

app/components/ErrorBoundary/ErrorBoundary.tsx
constants/bots.ts
lib/jwt.ts
types/bots.ts

Add new threat level handling for ATA exploiters.

PROD-989: Add new threat level handling for ATA exploiters

---

__tests__/queries/getValidationRewardQuestion.test.ts
app/queries/getValidationRewardQuestion.ts
lib/bonk/rateLimiter.ts
yarn.lock

Updated query to ignore questionIds for mystery box without percentage.

Prod 1059: Mystery fix handle question without percentage updated

---

app/api/v1/questions/route.ts
app/schemas/v1/question.ts
app/v1/questions/route.ts

Description:
- parse source
- parse backend-secret and use for security
- update schema of request
- move /api/v1 -> /v1
In order to test, you can send:
```
curl --request POST \
--url https://chomp-prod-main-d221483.d2.zuplo.dev/v1/questions \
--header 'authorization: Bearer API_TOKEN' \
--header 'Content-Type: application/json' \
--data '
{
"title": "The CIA ran a mind control project called MK-Ultra.",
"options": [
{
"title": "Conspiracy",
"index": 0
},
{
"title": "Real",
"index": 1
}
],
"activeAt": "2025-05-01T00:00:00Z",
"resolvesAt": "2025-05-02T00:00:00Z",
"description": "From lizard people to leaked documents, some theories are pure fiction—others turned out to be true. Can you tell what is real and what is conspiracy cap?"
}
'
```

feat: API metadata and security

---

__tests__/actions/mystery-box-history.test.ts
app/actions/mysteryBox/dismiss.ts
app/actions/mysteryBox/open.ts
app/actions/mysteryBox/reveal.ts
app/api/cron/detect-bonk-owed/route.ts
app/api/cron/detect-bonk-owned/route.ts
app/utils/date.ts
scripts/mystery-box/README.md
scripts/mystery-box/mystery-box-find-unsuccessful-prizes.ts
scripts/mystery-box/results-clean-false-positives.ts
vercel.json

Run the script to detect problematic MysteryBoxPrizes daily and report it to Slack, created an api and a vercel cron
also 
refactored the scripts/mystery-box/mystery-box-find-unsuccessful-prizes.ts to be simpler and "single thread"

PROD-968 fix-steady-state-bonk-owed

---

__tests__/actions/question/generateTestQuestion.test.ts
app/actions/question/generateTestQuestion.ts

PROD-1085: multi question generation from admin panel

---

__tests__/lib/v1/answerQuestion.test.ts
__tests__/v1/questions/answer.route.test.ts
app/schemas/v1/answer.ts
lib/v1/answerQuestion.ts
prisma/migrations/20250512220851_add_weight_column_to_questionanswer/migration.sql
prisma/schema.prisma

Implement weight field for QuestionAnswer.

PROD-1089: Implement weight field for QuestionAnswer.

---

__tests__/v1/questions/update.route.test.ts
app/schemas/v1/update.ts
app/v1/questions/[id]/route.ts
lib/v1/updateQuestion.ts

PROD-1068: update question API endpoint

---

__tests__/lib/answerStats/getStats.test.ts
lib/answerStats/getStats.ts

Fix reward display and answer page inconsistency issue.

PROD-1104: Fix reward display and answer page inconsistency issue

---

app/v1/questions/[id]/answer/route.ts

Hotfix release.
[fix](https://github.com/gator-labs/chomp/pull/1156): Fix incorrect rewards on answer page.

Release: May 13, 2025

---

lib/auth.ts
lib/credits/chargeUserCredits.ts

I originally intended to open https://github.com/gator-labs/chomp/pull/1163 into `prod` branch.

release(hotfix): jwks

---

__tests__/lib/ask/getCommunityAskStats.test.ts
app/admin/ask-inbox/page.tsx
app/api/ask/stats/route.ts
components/CommunityAskList/CommunityAskListItem.tsx
components/CommunityAskList/CommunityAskStats.tsx
hooks/useCommunityAskStatsQuery.ts
lib/ask/getCommunityAskStats.ts

PROD-1096: Add ask stats to admin panel

---

app/schemas/v1/answer.ts
app/v1/questions/[id]/answer/route.ts

Make weight parameter optional in answer API.

PROD-1117: Make weight parameter optional in answer API.

---

prisma/migrations/20250519174700_update_question_status_views/migration.sql

Fix answer status view/migration.

Remove prefix from CTE table.

---

__tests__/actions/answer/answer-credit.test.ts

Fix test for exception error message.

Fix test for exception error message.

---

__tests__/lib/credits/chargeUserCredits.test.ts
__tests__/lib/v1/answerQuestion.test.ts
__tests__/v1/questions/answer.route.test.ts
__tests__/v1/questions/getQuestions.test.ts
__tests__/v1/questions/route.get-question.test.ts
__tests__/v1/questions/update.route.test.ts
app/queries/leaderboard.ts
app/v1/questions/[id]/route.ts
app/v1/questions/route.ts
lib/auth.ts
lib/v1/answerQuestion.ts
prisma/migrations/20250523112528_add_index_question_answer_question_option_id_question_option_question_id/migration.sql
prisma/schema.prisma

File with actual changes -->
1. leaderboard.ts
2. migration.sql
3. schema.prisma
Other files include lint fixes 
Failing test seems to be unrelated.

Fix slow getAllTimeChompedQuestionsQuery query

---

__tests__/lib/ask/addToCommunityAskList.test.ts
app/admin/ask-inbox/page.tsx
app/api/ask/decks/route.ts
app/api/ask/route.ts
components/CommunityAskList/CommunityAskList.tsx
components/CommunityAskList/CommunityAskListItem.tsx
hooks/useCommunityAskAddToDeck.tsx
hooks/useCommunityAskDecksQuery.ts
lib/ask/addToCommunityDeck.ts
lib/ask/createCommunityDeck.ts
lib/ask/getCommunityAskDecks.ts
types/ask.ts

Allow multiple community decks to be created. Implements a modal with on-the-fly creation capability.

PROD-1143: Allow creation of multiple community decks simultaneously

---

__tests__/queries/home/streak.test.ts
app/admin/users/page.tsx
app/api/streak/route.ts
app/queries/home.ts
components/UserGiveCredits.tsx
components/UserRepairStreak.tsx
components/UserViewStreakInfo.tsx
hooks/useGetUserStreakQuery.ts
hooks/useRepairUserStreak.ts
lib/streaks/getUserStreak.ts
lib/streaks/repairStreak.ts
prisma/migrations/20250616233028_create_streakextension_table/migration.sql
prisma/schema.prisma

Implement streak extensions/repair.

PROD-1156: Streak extensions

---

components/CommunityAskList/CommunityAskListItem.tsx

Ask admin panel: default to create deck form if no decks in list.

Ask admin panel: default to create deck form if no decks in list.
